// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MM_computeTiles (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_stream_dout,
        A_stream_empty_n,
        A_stream_read,
        B_stream_dout,
        B_stream_empty_n,
        B_stream_read,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        C,
        AB_stream_din,
        AB_stream_full_n,
        AB_stream_write,
        AB_stream_num_data_valid,
        AB_stream_fifo_cap,
        N,
        M,
        P
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] A_stream_dout;
input   A_stream_empty_n;
output   A_stream_read;
input  [511:0] B_stream_dout;
input   B_stream_empty_n;
output   B_stream_read;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [511:0] m_axi_gmem_0_WDATA;
output  [63:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [511:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [63:0] C;
output  [511:0] AB_stream_din;
input   AB_stream_full_n;
output   AB_stream_write;
input  [31:0] AB_stream_num_data_valid;
input  [31:0] AB_stream_fifo_cap;
input  [31:0] N;
input  [31:0] M;
input  [31:0] P;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_0_ARVALID;
reg[63:0] m_axi_gmem_0_ARADDR;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
reg   [511:0] reg_346;
wire   [27:0] div_fu_390_p3;
reg   [27:0] div_reg_1954;
wire   [27:0] div2_fu_438_p3;
reg   [27:0] div2_reg_1959;
wire   [511:0] p_cast492_fu_612_p1;
reg   [511:0] p_cast492_reg_1964;
wire   [511:0] p_cast493_fu_624_p1;
reg   [511:0] p_cast493_reg_1969;
wire   [511:0] p_cast494_fu_636_p1;
reg   [511:0] p_cast494_reg_1974;
wire   [511:0] p_cast495_fu_648_p1;
reg   [511:0] p_cast495_reg_1979;
wire   [511:0] p_cast496_fu_660_p1;
reg   [511:0] p_cast496_reg_1984;
wire   [511:0] p_cast497_fu_672_p1;
reg   [511:0] p_cast497_reg_1989;
wire   [511:0] p_cast498_fu_684_p1;
reg   [511:0] p_cast498_reg_1994;
wire   [511:0] p_cast499_fu_696_p1;
reg   [511:0] p_cast499_reg_1999;
wire   [511:0] p_cast500_fu_710_p1;
reg   [511:0] p_cast500_reg_2004;
wire   [511:0] p_cast501_fu_722_p1;
reg   [511:0] p_cast501_reg_2009;
wire   [511:0] p_cast502_fu_734_p1;
reg   [511:0] p_cast502_reg_2014;
wire   [511:0] p_cast503_fu_746_p1;
reg   [511:0] p_cast503_reg_2019;
wire   [511:0] p_cast504_fu_758_p1;
reg   [511:0] p_cast504_reg_2024;
wire   [511:0] p_cast505_fu_770_p1;
reg   [511:0] p_cast505_reg_2029;
wire   [511:0] p_cast506_fu_782_p1;
reg   [511:0] p_cast506_reg_2034;
wire   [511:0] zext_ln65_fu_794_p1;
reg   [511:0] zext_ln65_reg_2039;
wire   [34:0] tmp_37_fu_812_p3;
reg   [34:0] tmp_37_reg_2044;
wire   [26:0] add_ln65_14_fu_837_p2;
reg   [26:0] add_ln65_14_reg_2052;
wire    ap_CS_fsm_state2;
wire   [63:0] empty_47_fu_855_p2;
reg   [63:0] empty_47_reg_2057;
reg   [57:0] p_cast_reg_2076;
reg   [57:0] p_cast2_reg_2087;
reg   [57:0] p_cast4_reg_2098;
reg   [57:0] p_cast6_reg_2109;
reg   [57:0] p_cast8_reg_2120;
reg   [57:0] p_cast1_reg_2131;
reg   [57:0] p_cast3_reg_2142;
reg   [57:0] p_cast5_reg_2153;
reg   [57:0] p_cast7_reg_2164;
reg   [57:0] p_cast9_reg_2175;
wire   [31:0] empty_49_fu_1100_p1;
reg   [31:0] empty_49_reg_2180;
reg   [57:0] p_cast10_reg_2206;
wire   [31:0] empty_52_fu_1134_p1;
reg   [31:0] empty_52_reg_2211;
reg   [57:0] p_cast11_reg_2237;
wire   [31:0] empty_55_fu_1168_p1;
reg   [31:0] empty_55_reg_2242;
reg   [57:0] p_cast12_reg_2268;
wire   [31:0] empty_58_fu_1202_p1;
reg   [31:0] empty_58_reg_2273;
reg   [57:0] p_cast13_reg_2299;
wire   [31:0] empty_61_fu_1236_p1;
reg   [31:0] empty_61_reg_2304;
reg   [57:0] p_cast14_reg_2330;
reg   [57:0] p_cast15_reg_2335;
wire   [31:0] empty_64_fu_1285_p1;
reg   [31:0] empty_64_reg_2340;
wire   [31:0] empty_67_fu_1304_p1;
reg   [31:0] empty_67_reg_2366;
wire   [31:0] empty_70_fu_1323_p1;
reg   [31:0] empty_70_reg_2392;
wire   [31:0] empty_73_fu_1332_p1;
reg   [31:0] empty_73_reg_2412;
wire   [31:0] empty_76_fu_1341_p1;
reg   [31:0] empty_76_reg_2432;
wire   [31:0] empty_79_fu_1350_p1;
reg   [31:0] empty_79_reg_2452;
wire   [31:0] empty_82_fu_1359_p1;
reg   [31:0] empty_82_reg_2472;
wire   [31:0] empty_85_fu_1368_p1;
reg   [31:0] empty_85_reg_2492;
wire   [31:0] empty_88_fu_1377_p1;
reg   [31:0] empty_88_reg_2512;
wire   [31:0] empty_91_fu_1386_p1;
reg   [31:0] empty_91_reg_2532;
wire   [511:0] thr_or_fu_1399_p17;
reg   [511:0] thr_or_reg_2552;
wire    ap_CS_fsm_state27;
wire   [511:0] thr_or1_fu_1419_p17;
reg   [511:0] thr_or1_reg_2557;
wire   [511:0] thr_or2_fu_1439_p17;
reg   [511:0] thr_or2_reg_2562;
wire   [511:0] thr_or3_fu_1459_p17;
reg   [511:0] thr_or3_reg_2567;
wire   [511:0] thr_or4_fu_1479_p17;
reg   [511:0] thr_or4_reg_2572;
wire   [511:0] thr_or5_fu_1499_p17;
reg   [511:0] thr_or5_reg_2577;
wire   [511:0] thr_or6_fu_1519_p17;
reg   [511:0] thr_or6_reg_2582;
wire   [511:0] thr_or7_fu_1539_p17;
reg   [511:0] thr_or7_reg_2587;
wire   [511:0] thr_or8_fu_1559_p17;
reg   [511:0] thr_or8_reg_2592;
wire   [511:0] thr_or9_fu_1579_p17;
reg   [511:0] thr_or9_reg_2597;
wire   [511:0] thr_or10_fu_1599_p17;
reg   [511:0] thr_or10_reg_2602;
wire   [511:0] thr_or11_fu_1619_p17;
reg   [511:0] thr_or11_reg_2607;
wire   [511:0] thr_or12_fu_1639_p17;
reg   [511:0] thr_or12_reg_2612;
wire   [511:0] thr_or13_fu_1659_p17;
reg   [511:0] thr_or13_reg_2617;
wire   [511:0] thr_or14_fu_1679_p17;
reg   [511:0] thr_or14_reg_2622;
wire   [511:0] thr_or15_fu_1699_p17;
reg   [511:0] thr_or15_reg_2627;
wire   [26:0] add_ln67_fu_1744_p2;
reg   [26:0] add_ln67_reg_2635;
wire    ap_CS_fsm_state28;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_done;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_idle;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_ready;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_A_stream_read;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_B_stream_read;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_15_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_15_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_14_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_14_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_13_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_13_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_12_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_12_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_11_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_11_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_10_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_10_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_9_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_9_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_8_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_8_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_7_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_7_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_6_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_6_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_5_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_5_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_4_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_4_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_3_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_3_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_2_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_2_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_1_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_1_2_out_ap_vld;
wire   [511:0] grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_0_2_out;
wire    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_0_2_out_ap_vld;
wire    grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start;
wire    grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_done;
wire    grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_idle;
wire    grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_ready;
wire   [511:0] grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_din;
wire    grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_write;
reg   [26:0] jb_reg_272;
wire    ap_CS_fsm_state31;
reg    grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg;
wire   [0:0] icmp_ln67_fu_1739_p2;
wire    ap_CS_fsm_state29;
reg    grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg;
wire    ap_CS_fsm_state30;
wire  signed [63:0] p_cast_cast_fu_870_p1;
wire  signed [63:0] p_cast15_cast_fu_895_p1;
wire  signed [63:0] p_cast17_cast_fu_920_p1;
wire  signed [63:0] p_cast19_cast_fu_945_p1;
wire  signed [63:0] p_cast21_cast_fu_970_p1;
wire  signed [63:0] p_cast23_cast_fu_995_p1;
wire  signed [63:0] p_cast25_cast_fu_1020_p1;
wire  signed [63:0] p_cast27_cast_fu_1045_p1;
wire  signed [63:0] p_cast29_cast_fu_1070_p1;
wire  signed [63:0] p_cast31_cast_fu_1104_p1;
wire  signed [63:0] p_cast33_cast_fu_1138_p1;
wire  signed [63:0] p_cast35_cast_fu_1172_p1;
wire  signed [63:0] p_cast37_cast_fu_1206_p1;
wire  signed [63:0] p_cast39_cast_fu_1240_p1;
wire  signed [63:0] p_cast41_cast_fu_1289_p1;
wire  signed [63:0] p_cast43_cast_fu_1308_p1;
reg   [26:0] ib_fu_168;
wire   [31:0] p_neg9_fu_358_p2;
wire   [27:0] tmp_fu_364_p4;
wire   [0:0] tmp_28_fu_350_p3;
wire   [27:0] p_neg_t11_fu_374_p2;
wire   [27:0] tmp_s_fu_380_p4;
wire   [31:0] p_neg3_fu_406_p2;
wire   [27:0] tmp_16_fu_412_p4;
wire   [0:0] tmp_47_fu_398_p3;
wire   [27:0] p_neg_t5_fu_422_p2;
wire   [27:0] tmp_17_fu_428_p4;
wire   [31:0] p_neg_fu_454_p2;
wire   [27:0] tmp_18_fu_460_p4;
wire   [0:0] tmp_48_fu_446_p3;
wire   [27:0] p_neg_t_fu_470_p2;
wire   [27:0] tmp_19_fu_476_p4;
wire   [27:0] div20_fu_486_p3;
wire   [5:0] trunc_ln65_1_fu_498_p1;
wire   [0:0] bit_sel_fu_544_p3;
wire   [8:0] tmp_20_fu_604_p3;
wire   [5:0] add_ln65_fu_502_p2;
wire   [8:0] tmp_21_fu_616_p3;
wire   [5:0] add_ln65_1_fu_508_p2;
wire   [8:0] tmp_22_fu_628_p3;
wire   [5:0] add_ln65_2_fu_514_p2;
wire   [8:0] tmp_23_fu_640_p3;
wire   [5:0] add_ln65_3_fu_520_p2;
wire   [8:0] tmp_24_fu_652_p3;
wire   [5:0] add_ln65_4_fu_526_p2;
wire   [8:0] tmp_25_fu_664_p3;
wire   [5:0] add_ln65_5_fu_532_p2;
wire   [8:0] tmp_26_fu_676_p3;
wire   [5:0] add_ln65_6_fu_538_p2;
wire   [8:0] tmp_27_fu_688_p3;
wire   [0:0] xor_ln65_fu_552_p2;
wire   [4:0] trunc_ln65_2_fu_558_p1;
wire   [8:0] tmp_29_fu_700_p4;
wire   [5:0] add_ln65_7_fu_562_p2;
wire   [8:0] tmp_30_fu_714_p3;
wire   [5:0] add_ln65_8_fu_568_p2;
wire   [8:0] tmp_31_fu_726_p3;
wire   [5:0] add_ln65_9_fu_574_p2;
wire   [8:0] tmp_32_fu_738_p3;
wire   [5:0] add_ln65_10_fu_580_p2;
wire   [8:0] tmp_33_fu_750_p3;
wire   [5:0] add_ln65_11_fu_586_p2;
wire   [8:0] tmp_34_fu_762_p3;
wire   [5:0] add_ln65_12_fu_592_p2;
wire   [8:0] tmp_35_fu_774_p3;
wire   [5:0] add_ln65_13_fu_598_p2;
wire   [8:0] tmp_36_fu_786_p3;
wire   [0:0] empty_fu_798_p2;
wire   [26:0] trunc_ln65_fu_494_p1;
wire   [26:0] empty_46_fu_804_p3;
wire   [27:0] zext_ln65_1_fu_828_p1;
wire   [32:0] tmp_38_fu_843_p3;
wire   [63:0] p_cast508_fu_851_p1;
wire   [63:0] empty_50_fu_880_p2;
wire   [63:0] empty_53_fu_905_p2;
wire   [63:0] empty_56_fu_930_p2;
wire   [63:0] empty_59_fu_955_p2;
wire   [63:0] empty_62_fu_980_p2;
wire   [63:0] empty_65_fu_1005_p2;
wire   [63:0] empty_68_fu_1030_p2;
wire   [63:0] empty_71_fu_1055_p2;
wire   [63:0] empty_74_fu_1080_p2;
wire   [511:0] empty_48_fu_1095_p2;
wire   [63:0] empty_77_fu_1114_p2;
wire   [511:0] empty_51_fu_1129_p2;
wire   [63:0] empty_80_fu_1148_p2;
wire   [511:0] empty_54_fu_1163_p2;
wire   [63:0] empty_83_fu_1182_p2;
wire   [511:0] empty_57_fu_1197_p2;
wire   [63:0] empty_86_fu_1216_p2;
wire   [511:0] empty_60_fu_1231_p2;
wire   [63:0] empty_89_fu_1250_p2;
wire   [63:0] empty_92_fu_1265_p2;
wire   [511:0] empty_63_fu_1280_p2;
wire   [511:0] empty_66_fu_1299_p2;
wire   [511:0] empty_69_fu_1318_p2;
wire   [511:0] empty_72_fu_1327_p2;
wire   [511:0] empty_75_fu_1336_p2;
wire   [511:0] empty_78_fu_1345_p2;
wire   [511:0] empty_81_fu_1354_p2;
wire   [511:0] empty_84_fu_1363_p2;
wire   [511:0] empty_87_fu_1372_p2;
wire   [511:0] empty_90_fu_1381_p2;
wire   [511:0] empty_93_fu_1390_p2;
wire   [31:0] empty_94_fu_1395_p1;
wire   [27:0] zext_ln67_fu_1735_p1;
wire   [0:0] icmp_ln65_fu_832_p2;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg = 1'b0;
#0 grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg = 1'b0;
#0 ib_fu_168 = 27'd0;
end

MM_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start),
    .ap_done(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_done),
    .ap_idle(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_idle),
    .ap_ready(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_ready),
    .A_stream_dout(A_stream_dout),
    .A_stream_empty_n(A_stream_empty_n),
    .A_stream_read(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_A_stream_read),
    .B_stream_dout(B_stream_dout),
    .B_stream_empty_n(B_stream_empty_n),
    .B_stream_read(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_B_stream_read),
    .thr_or15(thr_or15_reg_2627),
    .thr_or14(thr_or14_reg_2622),
    .thr_or13(thr_or13_reg_2617),
    .thr_or12(thr_or12_reg_2612),
    .thr_or11(thr_or11_reg_2607),
    .thr_or10(thr_or10_reg_2602),
    .thr_or9(thr_or9_reg_2597),
    .thr_or8(thr_or8_reg_2592),
    .thr_or7(thr_or7_reg_2587),
    .thr_or6(thr_or6_reg_2582),
    .thr_or5(thr_or5_reg_2577),
    .thr_or4(thr_or4_reg_2572),
    .thr_or3(thr_or3_reg_2567),
    .thr_or2(thr_or2_reg_2562),
    .thr_or1(thr_or1_reg_2557),
    .thr_or(thr_or_reg_2552),
    .tmp_45(tmp_37_reg_2044),
    .AB_block_15_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_15_2_out),
    .AB_block_15_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_15_2_out_ap_vld),
    .AB_block_14_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_14_2_out),
    .AB_block_14_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_14_2_out_ap_vld),
    .AB_block_13_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_13_2_out),
    .AB_block_13_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_13_2_out_ap_vld),
    .AB_block_12_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_12_2_out),
    .AB_block_12_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_12_2_out_ap_vld),
    .AB_block_11_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_11_2_out),
    .AB_block_11_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_11_2_out_ap_vld),
    .AB_block_10_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_10_2_out),
    .AB_block_10_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_10_2_out_ap_vld),
    .AB_block_9_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_9_2_out),
    .AB_block_9_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_9_2_out_ap_vld),
    .AB_block_8_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_8_2_out),
    .AB_block_8_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_8_2_out_ap_vld),
    .AB_block_7_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_7_2_out),
    .AB_block_7_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_7_2_out_ap_vld),
    .AB_block_6_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_6_2_out),
    .AB_block_6_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_6_2_out_ap_vld),
    .AB_block_5_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_5_2_out),
    .AB_block_5_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_5_2_out_ap_vld),
    .AB_block_4_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_4_2_out),
    .AB_block_4_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_4_2_out_ap_vld),
    .AB_block_3_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_3_2_out),
    .AB_block_3_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_3_2_out_ap_vld),
    .AB_block_2_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_2_2_out),
    .AB_block_2_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_2_2_out_ap_vld),
    .AB_block_1_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_1_2_out),
    .AB_block_1_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_1_2_out_ap_vld),
    .AB_block_0_2_out(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_0_2_out),
    .AB_block_0_2_out_ap_vld(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_0_2_out_ap_vld)
);

MM_computeTiles_Pipeline_j_output_loop grp_computeTiles_Pipeline_j_output_loop_fu_324(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start),
    .ap_done(grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_done),
    .ap_idle(grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_idle),
    .ap_ready(grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_ready),
    .AB_stream_din(grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_din),
    .AB_stream_full_n(AB_stream_full_n),
    .AB_stream_write(grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_write),
    .AB_stream_num_data_valid(AB_stream_num_data_valid),
    .AB_stream_fifo_cap(AB_stream_fifo_cap),
    .AB_block_0_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_0_2_out),
    .AB_block_1_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_1_2_out),
    .AB_block_2_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_2_2_out),
    .AB_block_3_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_3_2_out),
    .AB_block_4_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_4_2_out),
    .AB_block_5_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_5_2_out),
    .AB_block_6_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_6_2_out),
    .AB_block_7_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_7_2_out),
    .AB_block_8_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_8_2_out),
    .AB_block_9_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_9_2_out),
    .AB_block_10_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_10_2_out),
    .AB_block_11_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_11_2_out),
    .AB_block_12_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_12_2_out),
    .AB_block_13_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_13_2_out),
    .AB_block_14_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_14_2_out),
    .AB_block_15_2_reload(grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_AB_block_15_2_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state30)) begin
            grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg <= 1'b1;
        end else if ((grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_ready == 1'b1)) begin
            grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln67_fu_1739_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
            grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_ready == 1'b1)) begin
            grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ib_fu_168 <= 27'd0;
    end else if (((icmp_ln67_fu_1739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        ib_fu_168 <= add_ln65_14_reg_2052;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        jb_reg_272 <= add_ln67_reg_2635;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        jb_reg_272 <= 27'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln65_14_reg_2052 <= add_ln65_14_fu_837_p2;
        empty_47_reg_2057 <= empty_47_fu_855_p2;
        p_cast_reg_2076 <= {{empty_47_fu_855_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        add_ln67_reg_2635 <= add_ln67_fu_1744_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        div2_reg_1959 <= div2_fu_438_p3;
        div_reg_1954 <= div_fu_390_p3;
        p_cast492_reg_1964[8 : 3] <= p_cast492_fu_612_p1[8 : 3];
        p_cast493_reg_1969[8 : 3] <= p_cast493_fu_624_p1[8 : 3];
        p_cast494_reg_1974[8 : 3] <= p_cast494_fu_636_p1[8 : 3];
        p_cast495_reg_1979[8 : 3] <= p_cast495_fu_648_p1[8 : 3];
        p_cast496_reg_1984[8 : 3] <= p_cast496_fu_660_p1[8 : 3];
        p_cast497_reg_1989[8 : 3] <= p_cast497_fu_672_p1[8 : 3];
        p_cast498_reg_1994[8 : 3] <= p_cast498_fu_684_p1[8 : 3];
        p_cast499_reg_1999[8 : 3] <= p_cast499_fu_696_p1[8 : 3];
        p_cast500_reg_2004[8 : 3] <= p_cast500_fu_710_p1[8 : 3];
        p_cast501_reg_2009[8 : 3] <= p_cast501_fu_722_p1[8 : 3];
        p_cast502_reg_2014[8 : 3] <= p_cast502_fu_734_p1[8 : 3];
        p_cast503_reg_2019[8 : 3] <= p_cast503_fu_746_p1[8 : 3];
        p_cast504_reg_2024[8 : 3] <= p_cast504_fu_758_p1[8 : 3];
        p_cast505_reg_2029[8 : 3] <= p_cast505_fu_770_p1[8 : 3];
        p_cast506_reg_2034[8 : 3] <= p_cast506_fu_782_p1[8 : 3];
        tmp_37_reg_2044[34 : 8] <= tmp_37_fu_812_p3[34 : 8];
        zext_ln65_reg_2039[8 : 3] <= zext_ln65_fu_794_p1[8 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        empty_49_reg_2180 <= empty_49_fu_1100_p1;
        p_cast10_reg_2206 <= {{empty_77_fu_1114_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        empty_52_reg_2211 <= empty_52_fu_1134_p1;
        p_cast11_reg_2237 <= {{empty_80_fu_1148_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        empty_55_reg_2242 <= empty_55_fu_1168_p1;
        p_cast12_reg_2268 <= {{empty_83_fu_1182_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        empty_58_reg_2273 <= empty_58_fu_1202_p1;
        p_cast13_reg_2299 <= {{empty_86_fu_1216_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        empty_61_reg_2304 <= empty_61_fu_1236_p1;
        p_cast14_reg_2330 <= {{empty_89_fu_1250_p2[63:6]}};
        p_cast15_reg_2335 <= {{empty_92_fu_1265_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        empty_64_reg_2340 <= empty_64_fu_1285_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        empty_67_reg_2366 <= empty_67_fu_1304_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        empty_70_reg_2392 <= empty_70_fu_1323_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        empty_73_reg_2412 <= empty_73_fu_1332_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        empty_76_reg_2432 <= empty_76_fu_1341_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        empty_79_reg_2452 <= empty_79_fu_1350_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        empty_82_reg_2472 <= empty_82_fu_1359_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        empty_85_reg_2492 <= empty_85_fu_1368_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        empty_88_reg_2512 <= empty_88_fu_1377_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        empty_91_reg_2532 <= empty_91_fu_1386_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_cast1_reg_2131 <= {{empty_62_fu_980_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_cast2_reg_2087 <= {{empty_50_fu_880_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_cast3_reg_2142 <= {{empty_65_fu_1005_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_cast4_reg_2098 <= {{empty_53_fu_905_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_cast5_reg_2153 <= {{empty_68_fu_1030_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_cast6_reg_2109 <= {{empty_56_fu_930_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_cast7_reg_2164 <= {{empty_71_fu_1055_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_cast8_reg_2120 <= {{empty_59_fu_955_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        p_cast9_reg_2175 <= {{empty_74_fu_1080_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((m_axi_gmem_0_RVALID 
    == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state11)))) begin
        reg_346 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        thr_or10_reg_2602 <= thr_or10_fu_1599_p17;
        thr_or11_reg_2607 <= thr_or11_fu_1619_p17;
        thr_or12_reg_2612 <= thr_or12_fu_1639_p17;
        thr_or13_reg_2617 <= thr_or13_fu_1659_p17;
        thr_or14_reg_2622 <= thr_or14_fu_1679_p17;
        thr_or15_reg_2627 <= thr_or15_fu_1699_p17;
        thr_or1_reg_2557 <= thr_or1_fu_1419_p17;
        thr_or2_reg_2562 <= thr_or2_fu_1439_p17;
        thr_or3_reg_2567 <= thr_or3_fu_1459_p17;
        thr_or4_reg_2572 <= thr_or4_fu_1479_p17;
        thr_or5_reg_2577 <= thr_or5_fu_1499_p17;
        thr_or6_reg_2582 <= thr_or6_fu_1519_p17;
        thr_or7_reg_2587 <= thr_or7_fu_1539_p17;
        thr_or8_reg_2592 <= thr_or8_fu_1559_p17;
        thr_or9_reg_2597 <= thr_or9_fu_1579_p17;
        thr_or_reg_2552 <= thr_or_fu_1399_p17;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_done == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_done == 1'b0)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln65_fu_832_p2 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln65_fu_832_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_blk_n_AR = m_axi_gmem_0_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        m_axi_gmem_0_ARADDR = p_cast43_cast_fu_1308_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_gmem_0_ARADDR = p_cast41_cast_fu_1289_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state16))) begin
        m_axi_gmem_0_ARADDR = p_cast39_cast_fu_1240_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        m_axi_gmem_0_ARADDR = p_cast37_cast_fu_1206_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
        m_axi_gmem_0_ARADDR = p_cast35_cast_fu_1172_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem_0_ARADDR = p_cast33_cast_fu_1138_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        m_axi_gmem_0_ARADDR = p_cast31_cast_fu_1104_p1;
    end else if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
        m_axi_gmem_0_ARADDR = p_cast29_cast_fu_1070_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        m_axi_gmem_0_ARADDR = p_cast27_cast_fu_1045_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_0_ARADDR = p_cast25_cast_fu_1020_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem_0_ARADDR = p_cast23_cast_fu_995_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        m_axi_gmem_0_ARADDR = p_cast21_cast_fu_970_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        m_axi_gmem_0_ARADDR = p_cast19_cast_fu_945_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        m_axi_gmem_0_ARADDR = p_cast17_cast_fu_920_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem_0_ARADDR = p_cast15_cast_fu_895_p1;
    end else if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_0_ARADDR = p_cast_cast_fu_870_p1;
    end else begin
        m_axi_gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((m_axi_gmem_0_RVALID 
    == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state11)))) begin
        m_axi_gmem_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((m_axi_gmem_0_RVALID 
    == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state11)))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln65_fu_832_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((m_axi_gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if ((~((m_axi_gmem_0_RVALID == 1'b0) | (m_axi_gmem_0_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((m_axi_gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((icmp_ln67_fu_1739_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AB_stream_din = grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_din;

assign AB_stream_write = grp_computeTiles_Pipeline_j_output_loop_fu_324_AB_stream_write;

assign A_stream_read = grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_A_stream_read;

assign B_stream_read = grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_B_stream_read;

assign add_ln65_10_fu_580_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd48));

assign add_ln65_11_fu_586_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd52));

assign add_ln65_12_fu_592_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd56));

assign add_ln65_13_fu_598_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd60));

assign add_ln65_14_fu_837_p2 = (ib_fu_168 + 27'd1);

assign add_ln65_1_fu_508_p2 = (trunc_ln65_1_fu_498_p1 + 6'd8);

assign add_ln65_2_fu_514_p2 = (trunc_ln65_1_fu_498_p1 + 6'd12);

assign add_ln65_3_fu_520_p2 = (trunc_ln65_1_fu_498_p1 + 6'd16);

assign add_ln65_4_fu_526_p2 = (trunc_ln65_1_fu_498_p1 + 6'd20);

assign add_ln65_5_fu_532_p2 = (trunc_ln65_1_fu_498_p1 + 6'd24);

assign add_ln65_6_fu_538_p2 = (trunc_ln65_1_fu_498_p1 + 6'd28);

assign add_ln65_7_fu_562_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd36));

assign add_ln65_8_fu_568_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd40));

assign add_ln65_9_fu_574_p2 = ($signed(trunc_ln65_1_fu_498_p1) + $signed(6'd44));

assign add_ln65_fu_502_p2 = (trunc_ln65_1_fu_498_p1 + 6'd4);

assign add_ln67_fu_1744_p2 = (jb_reg_272 + 27'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bit_sel_fu_544_p3 = C[32'd5];

assign div20_fu_486_p3 = ((tmp_48_fu_446_p3[0:0] == 1'b1) ? p_neg_t_fu_470_p2 : tmp_19_fu_476_p4);

assign div2_fu_438_p3 = ((tmp_47_fu_398_p3[0:0] == 1'b1) ? p_neg_t5_fu_422_p2 : tmp_17_fu_428_p4);

assign div_fu_390_p3 = ((tmp_28_fu_350_p3[0:0] == 1'b1) ? p_neg_t11_fu_374_p2 : tmp_s_fu_380_p4);

assign empty_46_fu_804_p3 = ((empty_fu_798_p2[0:0] == 1'b1) ? trunc_ln65_fu_494_p1 : 27'd0);

assign empty_47_fu_855_p2 = (p_cast508_fu_851_p1 + C);

assign empty_48_fu_1095_p2 = reg_346 >> p_cast492_reg_1964;

assign empty_49_fu_1100_p1 = empty_48_fu_1095_p2[31:0];

assign empty_50_fu_880_p2 = (empty_47_reg_2057 + 64'd4);

assign empty_51_fu_1129_p2 = reg_346 >> p_cast493_reg_1969;

assign empty_52_fu_1134_p1 = empty_51_fu_1129_p2[31:0];

assign empty_53_fu_905_p2 = (empty_47_reg_2057 + 64'd8);

assign empty_54_fu_1163_p2 = reg_346 >> p_cast494_reg_1974;

assign empty_55_fu_1168_p1 = empty_54_fu_1163_p2[31:0];

assign empty_56_fu_930_p2 = (empty_47_reg_2057 + 64'd12);

assign empty_57_fu_1197_p2 = reg_346 >> p_cast495_reg_1979;

assign empty_58_fu_1202_p1 = empty_57_fu_1197_p2[31:0];

assign empty_59_fu_955_p2 = (empty_47_reg_2057 + 64'd16);

assign empty_60_fu_1231_p2 = reg_346 >> p_cast496_reg_1984;

assign empty_61_fu_1236_p1 = empty_60_fu_1231_p2[31:0];

assign empty_62_fu_980_p2 = (empty_47_reg_2057 + 64'd20);

assign empty_63_fu_1280_p2 = reg_346 >> p_cast497_reg_1989;

assign empty_64_fu_1285_p1 = empty_63_fu_1280_p2[31:0];

assign empty_65_fu_1005_p2 = (empty_47_reg_2057 + 64'd24);

assign empty_66_fu_1299_p2 = reg_346 >> p_cast498_reg_1994;

assign empty_67_fu_1304_p1 = empty_66_fu_1299_p2[31:0];

assign empty_68_fu_1030_p2 = (empty_47_reg_2057 + 64'd28);

assign empty_69_fu_1318_p2 = reg_346 >> p_cast499_reg_1999;

assign empty_70_fu_1323_p1 = empty_69_fu_1318_p2[31:0];

assign empty_71_fu_1055_p2 = (empty_47_reg_2057 + 64'd32);

assign empty_72_fu_1327_p2 = reg_346 >> p_cast500_reg_2004;

assign empty_73_fu_1332_p1 = empty_72_fu_1327_p2[31:0];

assign empty_74_fu_1080_p2 = (empty_47_reg_2057 + 64'd36);

assign empty_75_fu_1336_p2 = reg_346 >> p_cast501_reg_2009;

assign empty_76_fu_1341_p1 = empty_75_fu_1336_p2[31:0];

assign empty_77_fu_1114_p2 = (empty_47_reg_2057 + 64'd40);

assign empty_78_fu_1345_p2 = reg_346 >> p_cast502_reg_2014;

assign empty_79_fu_1350_p1 = empty_78_fu_1345_p2[31:0];

assign empty_80_fu_1148_p2 = (empty_47_reg_2057 + 64'd44);

assign empty_81_fu_1354_p2 = reg_346 >> p_cast503_reg_2019;

assign empty_82_fu_1359_p1 = empty_81_fu_1354_p2[31:0];

assign empty_83_fu_1182_p2 = (empty_47_reg_2057 + 64'd48);

assign empty_84_fu_1363_p2 = reg_346 >> p_cast504_reg_2024;

assign empty_85_fu_1368_p1 = empty_84_fu_1363_p2[31:0];

assign empty_86_fu_1216_p2 = (empty_47_reg_2057 + 64'd52);

assign empty_87_fu_1372_p2 = reg_346 >> p_cast505_reg_2029;

assign empty_88_fu_1377_p1 = empty_87_fu_1372_p2[31:0];

assign empty_89_fu_1250_p2 = (empty_47_reg_2057 + 64'd56);

assign empty_90_fu_1381_p2 = reg_346 >> p_cast506_reg_2034;

assign empty_91_fu_1386_p1 = empty_90_fu_1381_p2[31:0];

assign empty_92_fu_1265_p2 = (empty_47_reg_2057 + 64'd60);

assign empty_93_fu_1390_p2 = reg_346 >> zext_ln65_reg_2039;

assign empty_94_fu_1395_p1 = empty_93_fu_1390_p2[31:0];

assign empty_fu_798_p2 = (($signed(div20_fu_486_p3) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start = grp_computeTiles_Pipeline_j_output_loop_fu_324_ap_start_reg;

assign grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start = grp_computeTiles_Pipeline_k_BLOCK_loop_k_loop_i_loop_fu_283_ap_start_reg;

assign icmp_ln65_fu_832_p2 = (($signed(zext_ln65_1_fu_828_p1) < $signed(div_reg_1954)) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_1739_p2 = (($signed(zext_ln67_fu_1735_p1) < $signed(div2_reg_1959)) ? 1'b1 : 1'b0);

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 64'd1;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 512'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 64'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign p_cast15_cast_fu_895_p1 = $signed(p_cast2_reg_2087);

assign p_cast17_cast_fu_920_p1 = $signed(p_cast4_reg_2098);

assign p_cast19_cast_fu_945_p1 = $signed(p_cast6_reg_2109);

assign p_cast21_cast_fu_970_p1 = $signed(p_cast8_reg_2120);

assign p_cast23_cast_fu_995_p1 = $signed(p_cast1_reg_2131);

assign p_cast25_cast_fu_1020_p1 = $signed(p_cast3_reg_2142);

assign p_cast27_cast_fu_1045_p1 = $signed(p_cast5_reg_2153);

assign p_cast29_cast_fu_1070_p1 = $signed(p_cast7_reg_2164);

assign p_cast31_cast_fu_1104_p1 = $signed(p_cast9_reg_2175);

assign p_cast33_cast_fu_1138_p1 = $signed(p_cast10_reg_2206);

assign p_cast35_cast_fu_1172_p1 = $signed(p_cast11_reg_2237);

assign p_cast37_cast_fu_1206_p1 = $signed(p_cast12_reg_2268);

assign p_cast39_cast_fu_1240_p1 = $signed(p_cast13_reg_2299);

assign p_cast41_cast_fu_1289_p1 = $signed(p_cast14_reg_2330);

assign p_cast43_cast_fu_1308_p1 = $signed(p_cast15_reg_2335);

assign p_cast492_fu_612_p1 = tmp_20_fu_604_p3;

assign p_cast493_fu_624_p1 = tmp_21_fu_616_p3;

assign p_cast494_fu_636_p1 = tmp_22_fu_628_p3;

assign p_cast495_fu_648_p1 = tmp_23_fu_640_p3;

assign p_cast496_fu_660_p1 = tmp_24_fu_652_p3;

assign p_cast497_fu_672_p1 = tmp_25_fu_664_p3;

assign p_cast498_fu_684_p1 = tmp_26_fu_676_p3;

assign p_cast499_fu_696_p1 = tmp_27_fu_688_p3;

assign p_cast500_fu_710_p1 = tmp_29_fu_700_p4;

assign p_cast501_fu_722_p1 = tmp_30_fu_714_p3;

assign p_cast502_fu_734_p1 = tmp_31_fu_726_p3;

assign p_cast503_fu_746_p1 = tmp_32_fu_738_p3;

assign p_cast504_fu_758_p1 = tmp_33_fu_750_p3;

assign p_cast505_fu_770_p1 = tmp_34_fu_762_p3;

assign p_cast506_fu_782_p1 = tmp_35_fu_774_p3;

assign p_cast508_fu_851_p1 = tmp_38_fu_843_p3;

assign p_cast_cast_fu_870_p1 = $signed(p_cast_reg_2076);

assign p_neg3_fu_406_p2 = (32'd0 - P);

assign p_neg9_fu_358_p2 = (32'd0 - N);

assign p_neg_fu_454_p2 = (32'd0 - M);

assign p_neg_t11_fu_374_p2 = (28'd0 - tmp_fu_364_p4);

assign p_neg_t5_fu_422_p2 = (28'd0 - tmp_16_fu_412_p4);

assign p_neg_t_fu_470_p2 = (28'd0 - tmp_18_fu_460_p4);

assign thr_or10_fu_1599_p17 = {{{{{{{{{{{{{{{{empty_79_reg_2452}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}}, {empty_79_reg_2452}};

assign thr_or11_fu_1619_p17 = {{{{{{{{{{{{{{{{empty_82_reg_2472}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}}, {empty_82_reg_2472}};

assign thr_or12_fu_1639_p17 = {{{{{{{{{{{{{{{{empty_85_reg_2492}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}}, {empty_85_reg_2492}};

assign thr_or13_fu_1659_p17 = {{{{{{{{{{{{{{{{empty_88_reg_2512}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}}, {empty_88_reg_2512}};

assign thr_or14_fu_1679_p17 = {{{{{{{{{{{{{{{{empty_91_reg_2532}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}}, {empty_91_reg_2532}};

assign thr_or15_fu_1699_p17 = {{{{{{{{{{{{{{{{empty_94_fu_1395_p1}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}}, {empty_94_fu_1395_p1}};

assign thr_or1_fu_1419_p17 = {{{{{{{{{{{{{{{{empty_52_reg_2211}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}}, {empty_52_reg_2211}};

assign thr_or2_fu_1439_p17 = {{{{{{{{{{{{{{{{empty_55_reg_2242}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}}, {empty_55_reg_2242}};

assign thr_or3_fu_1459_p17 = {{{{{{{{{{{{{{{{empty_58_reg_2273}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}}, {empty_58_reg_2273}};

assign thr_or4_fu_1479_p17 = {{{{{{{{{{{{{{{{empty_61_reg_2304}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}}, {empty_61_reg_2304}};

assign thr_or5_fu_1499_p17 = {{{{{{{{{{{{{{{{empty_64_reg_2340}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}}, {empty_64_reg_2340}};

assign thr_or6_fu_1519_p17 = {{{{{{{{{{{{{{{{empty_67_reg_2366}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}}, {empty_67_reg_2366}};

assign thr_or7_fu_1539_p17 = {{{{{{{{{{{{{{{{empty_70_reg_2392}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}}, {empty_70_reg_2392}};

assign thr_or8_fu_1559_p17 = {{{{{{{{{{{{{{{{empty_73_reg_2412}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}}, {empty_73_reg_2412}};

assign thr_or9_fu_1579_p17 = {{{{{{{{{{{{{{{{empty_76_reg_2432}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}}, {empty_76_reg_2432}};

assign thr_or_fu_1399_p17 = {{{{{{{{{{{{{{{{empty_49_reg_2180}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}}, {empty_49_reg_2180}};

assign tmp_16_fu_412_p4 = {{p_neg3_fu_406_p2[31:4]}};

assign tmp_17_fu_428_p4 = {{P[31:4]}};

assign tmp_18_fu_460_p4 = {{p_neg_fu_454_p2[31:4]}};

assign tmp_19_fu_476_p4 = {{M[31:4]}};

assign tmp_20_fu_604_p3 = {{trunc_ln65_1_fu_498_p1}, {3'd0}};

assign tmp_21_fu_616_p3 = {{add_ln65_fu_502_p2}, {3'd0}};

assign tmp_22_fu_628_p3 = {{add_ln65_1_fu_508_p2}, {3'd0}};

assign tmp_23_fu_640_p3 = {{add_ln65_2_fu_514_p2}, {3'd0}};

assign tmp_24_fu_652_p3 = {{add_ln65_3_fu_520_p2}, {3'd0}};

assign tmp_25_fu_664_p3 = {{add_ln65_4_fu_526_p2}, {3'd0}};

assign tmp_26_fu_676_p3 = {{add_ln65_5_fu_532_p2}, {3'd0}};

assign tmp_27_fu_688_p3 = {{add_ln65_6_fu_538_p2}, {3'd0}};

assign tmp_28_fu_350_p3 = N[32'd31];

assign tmp_29_fu_700_p4 = {{{xor_ln65_fu_552_p2}, {trunc_ln65_2_fu_558_p1}}, {3'd0}};

assign tmp_30_fu_714_p3 = {{add_ln65_7_fu_562_p2}, {3'd0}};

assign tmp_31_fu_726_p3 = {{add_ln65_8_fu_568_p2}, {3'd0}};

assign tmp_32_fu_738_p3 = {{add_ln65_9_fu_574_p2}, {3'd0}};

assign tmp_33_fu_750_p3 = {{add_ln65_10_fu_580_p2}, {3'd0}};

assign tmp_34_fu_762_p3 = {{add_ln65_11_fu_586_p2}, {3'd0}};

assign tmp_35_fu_774_p3 = {{add_ln65_12_fu_592_p2}, {3'd0}};

assign tmp_36_fu_786_p3 = {{add_ln65_13_fu_598_p2}, {3'd0}};

assign tmp_37_fu_812_p3 = {{empty_46_fu_804_p3}, {8'd0}};

assign tmp_38_fu_843_p3 = {{ib_fu_168}, {6'd0}};

assign tmp_47_fu_398_p3 = P[32'd31];

assign tmp_48_fu_446_p3 = M[32'd31];

assign tmp_fu_364_p4 = {{p_neg9_fu_358_p2[31:4]}};

assign tmp_s_fu_380_p4 = {{N[31:4]}};

assign trunc_ln65_1_fu_498_p1 = C[5:0];

assign trunc_ln65_2_fu_558_p1 = C[4:0];

assign trunc_ln65_fu_494_p1 = div20_fu_486_p3[26:0];

assign xor_ln65_fu_552_p2 = (bit_sel_fu_544_p3 ^ 1'd1);

assign zext_ln65_1_fu_828_p1 = ib_fu_168;

assign zext_ln65_fu_794_p1 = tmp_36_fu_786_p3;

assign zext_ln67_fu_1735_p1 = jb_reg_272;

always @ (posedge ap_clk) begin
    p_cast492_reg_1964[2:0] <= 3'b000;
    p_cast492_reg_1964[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast493_reg_1969[2:0] <= 3'b000;
    p_cast493_reg_1969[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast494_reg_1974[2:0] <= 3'b000;
    p_cast494_reg_1974[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast495_reg_1979[2:0] <= 3'b000;
    p_cast495_reg_1979[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast496_reg_1984[2:0] <= 3'b000;
    p_cast496_reg_1984[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast497_reg_1989[2:0] <= 3'b000;
    p_cast497_reg_1989[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast498_reg_1994[2:0] <= 3'b000;
    p_cast498_reg_1994[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast499_reg_1999[2:0] <= 3'b000;
    p_cast499_reg_1999[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast500_reg_2004[2:0] <= 3'b000;
    p_cast500_reg_2004[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast501_reg_2009[2:0] <= 3'b000;
    p_cast501_reg_2009[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast502_reg_2014[2:0] <= 3'b000;
    p_cast502_reg_2014[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast503_reg_2019[2:0] <= 3'b000;
    p_cast503_reg_2019[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast504_reg_2024[2:0] <= 3'b000;
    p_cast504_reg_2024[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast505_reg_2029[2:0] <= 3'b000;
    p_cast505_reg_2029[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    p_cast506_reg_2034[2:0] <= 3'b000;
    p_cast506_reg_2034[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    zext_ln65_reg_2039[2:0] <= 3'b000;
    zext_ln65_reg_2039[511:9] <= 503'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    tmp_37_reg_2044[7:0] <= 8'b00000000;
end

endmodule //MM_computeTiles
