// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MM_writeTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_j_output_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        AB_stream_dout,
        AB_stream_empty_n,
        AB_stream_read,
        AB_stream_num_data_valid,
        AB_stream_fifo_cap,
        m_axi_gmem3_0_AWVALID,
        m_axi_gmem3_0_AWREADY,
        m_axi_gmem3_0_AWADDR,
        m_axi_gmem3_0_AWID,
        m_axi_gmem3_0_AWLEN,
        m_axi_gmem3_0_AWSIZE,
        m_axi_gmem3_0_AWBURST,
        m_axi_gmem3_0_AWLOCK,
        m_axi_gmem3_0_AWCACHE,
        m_axi_gmem3_0_AWPROT,
        m_axi_gmem3_0_AWQOS,
        m_axi_gmem3_0_AWREGION,
        m_axi_gmem3_0_AWUSER,
        m_axi_gmem3_0_WVALID,
        m_axi_gmem3_0_WREADY,
        m_axi_gmem3_0_WDATA,
        m_axi_gmem3_0_WSTRB,
        m_axi_gmem3_0_WLAST,
        m_axi_gmem3_0_WID,
        m_axi_gmem3_0_WUSER,
        m_axi_gmem3_0_ARVALID,
        m_axi_gmem3_0_ARREADY,
        m_axi_gmem3_0_ARADDR,
        m_axi_gmem3_0_ARID,
        m_axi_gmem3_0_ARLEN,
        m_axi_gmem3_0_ARSIZE,
        m_axi_gmem3_0_ARBURST,
        m_axi_gmem3_0_ARLOCK,
        m_axi_gmem3_0_ARCACHE,
        m_axi_gmem3_0_ARPROT,
        m_axi_gmem3_0_ARQOS,
        m_axi_gmem3_0_ARREGION,
        m_axi_gmem3_0_ARUSER,
        m_axi_gmem3_0_RVALID,
        m_axi_gmem3_0_RREADY,
        m_axi_gmem3_0_RDATA,
        m_axi_gmem3_0_RLAST,
        m_axi_gmem3_0_RID,
        m_axi_gmem3_0_RFIFONUM,
        m_axi_gmem3_0_RUSER,
        m_axi_gmem3_0_RRESP,
        m_axi_gmem3_0_BVALID,
        m_axi_gmem3_0_BREADY,
        m_axi_gmem3_0_BRESP,
        m_axi_gmem3_0_BID,
        m_axi_gmem3_0_BUSER,
        tmp_4,
        bound6,
        N_1,
        ABC_load
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] AB_stream_dout;
input   AB_stream_empty_n;
output   AB_stream_read;
input  [5:0] AB_stream_num_data_valid;
input  [5:0] AB_stream_fifo_cap;
output   m_axi_gmem3_0_AWVALID;
input   m_axi_gmem3_0_AWREADY;
output  [63:0] m_axi_gmem3_0_AWADDR;
output  [0:0] m_axi_gmem3_0_AWID;
output  [31:0] m_axi_gmem3_0_AWLEN;
output  [2:0] m_axi_gmem3_0_AWSIZE;
output  [1:0] m_axi_gmem3_0_AWBURST;
output  [1:0] m_axi_gmem3_0_AWLOCK;
output  [3:0] m_axi_gmem3_0_AWCACHE;
output  [2:0] m_axi_gmem3_0_AWPROT;
output  [3:0] m_axi_gmem3_0_AWQOS;
output  [3:0] m_axi_gmem3_0_AWREGION;
output  [0:0] m_axi_gmem3_0_AWUSER;
output   m_axi_gmem3_0_WVALID;
input   m_axi_gmem3_0_WREADY;
output  [511:0] m_axi_gmem3_0_WDATA;
output  [63:0] m_axi_gmem3_0_WSTRB;
output   m_axi_gmem3_0_WLAST;
output  [0:0] m_axi_gmem3_0_WID;
output  [0:0] m_axi_gmem3_0_WUSER;
output   m_axi_gmem3_0_ARVALID;
input   m_axi_gmem3_0_ARREADY;
output  [63:0] m_axi_gmem3_0_ARADDR;
output  [0:0] m_axi_gmem3_0_ARID;
output  [31:0] m_axi_gmem3_0_ARLEN;
output  [2:0] m_axi_gmem3_0_ARSIZE;
output  [1:0] m_axi_gmem3_0_ARBURST;
output  [1:0] m_axi_gmem3_0_ARLOCK;
output  [3:0] m_axi_gmem3_0_ARCACHE;
output  [2:0] m_axi_gmem3_0_ARPROT;
output  [3:0] m_axi_gmem3_0_ARQOS;
output  [3:0] m_axi_gmem3_0_ARREGION;
output  [0:0] m_axi_gmem3_0_ARUSER;
input   m_axi_gmem3_0_RVALID;
output   m_axi_gmem3_0_RREADY;
input  [511:0] m_axi_gmem3_0_RDATA;
input   m_axi_gmem3_0_RLAST;
input  [0:0] m_axi_gmem3_0_RID;
input  [8:0] m_axi_gmem3_0_RFIFONUM;
input  [0:0] m_axi_gmem3_0_RUSER;
input  [1:0] m_axi_gmem3_0_RRESP;
input   m_axi_gmem3_0_BVALID;
output   m_axi_gmem3_0_BREADY;
input  [1:0] m_axi_gmem3_0_BRESP;
input  [0:0] m_axi_gmem3_0_BID;
input  [0:0] m_axi_gmem3_0_BUSER;
input  [30:0] tmp_4;
input  [57:0] bound6;
input  [31:0] N_1;
input  [63:0] ABC_load;

reg ap_idle;
reg AB_stream_read;
reg m_axi_gmem3_0_AWVALID;
reg m_axi_gmem3_0_WVALID;
reg m_axi_gmem3_0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln123_fu_216_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    AB_stream_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    gmem3_blk_n_AW;
reg    gmem3_blk_n_W;
reg    gmem3_blk_n_B;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [33:0] bound_fu_184_p1;
reg   [33:0] bound_reg_519;
wire   [0:0] icmp_ln125_fu_236_p2;
reg   [0:0] icmp_ln125_reg_528;
reg   [0:0] icmp_ln125_reg_528_pp0_iter2_reg;
wire  signed [31:0] add_ln130_fu_307_p2;
reg  signed [31:0] add_ln130_reg_533;
wire   [31:0] mul_ln130_fu_180_p2;
reg   [31:0] mul_ln130_reg_538;
wire   [31:0] add_ln130_1_fu_377_p2;
reg   [31:0] add_ln130_1_reg_543;
reg   [57:0] trunc_ln130_1_reg_550;
reg   [511:0] AB_stream_read_reg_555;
wire  signed [63:0] sext_ln130_1_fu_459_p1;
reg    ap_block_pp0_stage0_01001_grp1;
reg   [4:0] j_fu_110;
wire   [4:0] j_1_fu_313_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [27:0] jb_fu_114;
wire   [27:0] select_ln125_1_fu_287_p3;
reg   [33:0] indvar_flatten_fu_118;
wire   [33:0] select_ln125_2_fu_325_p3;
reg   [27:0] ib_fu_122;
wire   [27:0] select_ln123_1_fu_362_p3;
reg   [57:0] indvar_flatten20_fu_126;
wire   [57:0] add_ln123_fu_230_p2;
wire   [0:0] icmp_ln127_fu_255_p2;
wire   [0:0] xor_ln123_fu_249_p2;
wire   [27:0] select_ln123_fu_241_p3;
wire   [0:0] and_ln123_fu_261_p2;
wire   [0:0] or_ln125_fu_273_p2;
wire   [27:0] jb_2_fu_267_p2;
wire   [4:0] select_ln125_fu_279_p3;
wire   [31:0] mul_fu_295_p3;
wire   [31:0] zext_ln127_fu_303_p1;
wire   [33:0] add_ln125_1_fu_319_p2;
wire   [27:0] add_ln123_1_fu_356_p2;
wire   [31:0] mul1_fu_369_p3;
wire   [31:0] sub_ln130_fu_394_p2;
wire   [27:0] tmp_5_fu_399_p4;
wire   [0:0] tmp_fu_387_p3;
wire   [27:0] sub_ln130_1_fu_409_p2;
wire   [27:0] tmp_6_fu_415_p4;
wire   [27:0] select_ln130_fu_424_p3;
wire   [33:0] shl_ln_fu_432_p3;
wire  signed [63:0] sext_ln130_fu_440_p1;
wire   [63:0] add_ln130_2_fu_444_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 j_fu_110 = 5'd0;
#0 jb_fu_114 = 28'd0;
#0 indvar_flatten_fu_118 = 34'd0;
#0 ib_fu_122 = 28'd0;
#0 indvar_flatten20_fu_126 = 58'd0;
#0 ap_done_reg = 1'b0;
end

MM_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U135(
    .din0(N_1),
    .din1(add_ln130_reg_533),
    .dout(mul_ln130_fu_180_p2)
);

MM_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ib_fu_122 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            ib_fu_122 <= select_ln123_1_fu_362_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_126 <= 58'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_216_p2 == 1'd0))) begin
            indvar_flatten20_fu_126 <= add_ln123_fu_230_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_118 <= 34'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_216_p2 == 1'd0))) begin
            indvar_flatten_fu_118 <= select_ln125_2_fu_325_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_110 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_216_p2 == 1'd0))) begin
            j_fu_110 <= j_1_fu_313_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            jb_fu_114 <= 28'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln123_fu_216_p2 == 1'd0))) begin
            jb_fu_114 <= select_ln125_1_fu_287_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        AB_stream_read_reg_555 <= AB_stream_dout;
        add_ln130_1_reg_543 <= add_ln130_1_fu_377_p2;
        mul_ln130_reg_538 <= mul_ln130_fu_180_p2;
        trunc_ln130_1_reg_550 <= {{add_ln130_2_fu_444_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln130_reg_533 <= add_ln130_fu_307_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        bound_reg_519[30 : 0] <= bound_fu_184_p1[30 : 0];
        icmp_ln125_reg_528 <= icmp_ln125_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln125_reg_528_pp0_iter2_reg <= icmp_ln125_reg_528;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        AB_stream_blk_n = AB_stream_empty_n;
    end else begin
        AB_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        AB_stream_read = 1'b1;
    end else begin
        AB_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln123_fu_216_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter10_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem3_blk_n_AW = m_axi_gmem3_0_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem3_blk_n_B = m_axi_gmem3_0_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem3_blk_n_W = m_axi_gmem3_0_WREADY;
    end else begin
        gmem3_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem3_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem3_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem3_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem3_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem3_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem3_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_1_fu_356_p2 = (ib_fu_122 + 28'd1);

assign add_ln123_fu_230_p2 = (indvar_flatten20_fu_126 + 58'd1);

assign add_ln125_1_fu_319_p2 = (indvar_flatten_fu_118 + 34'd1);

assign add_ln130_1_fu_377_p2 = (mul_ln130_reg_538 + mul1_fu_369_p3);

assign add_ln130_2_fu_444_p2 = ($signed(ABC_load) + $signed(sext_ln130_fu_440_p1));

assign add_ln130_fu_307_p2 = (mul_fu_295_p3 + zext_ln127_fu_303_p1);

assign and_ln123_fu_261_p2 = (xor_ln123_fu_249_p2 & icmp_ln127_fu_255_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem3_0_BVALID == 1'b0)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == AB_stream_empty_n)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem3_0_BVALID == 1'b0)) | ((m_axi_gmem3_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axi_gmem3_0_AWREADY == 1'b0) | (1'b0 == AB_stream_empty_n))));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem3_0_BVALID == 1'b0)) | ((m_axi_gmem3_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axi_gmem3_0_AWREADY == 1'b0) | (1'b0 == AB_stream_empty_n))));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem3_0_BVALID == 1'b0)) | ((m_axi_gmem3_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & ((m_axi_gmem3_0_AWREADY == 1'b0) | (1'b0 == AB_stream_empty_n))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bound_fu_184_p1 = tmp_4;

assign icmp_ln123_fu_216_p2 = ((indvar_flatten20_fu_126 == bound6) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_236_p2 = ((indvar_flatten_fu_118 == bound_reg_519) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_255_p2 = ((j_fu_110 == 5'd16) ? 1'b1 : 1'b0);

assign j_1_fu_313_p2 = (select_ln125_fu_279_p3 + 5'd1);

assign jb_2_fu_267_p2 = (select_ln123_fu_241_p3 + 28'd1);

assign m_axi_gmem3_0_ARADDR = 64'd0;

assign m_axi_gmem3_0_ARBURST = 2'd0;

assign m_axi_gmem3_0_ARCACHE = 4'd0;

assign m_axi_gmem3_0_ARID = 1'd0;

assign m_axi_gmem3_0_ARLEN = 32'd0;

assign m_axi_gmem3_0_ARLOCK = 2'd0;

assign m_axi_gmem3_0_ARPROT = 3'd0;

assign m_axi_gmem3_0_ARQOS = 4'd0;

assign m_axi_gmem3_0_ARREGION = 4'd0;

assign m_axi_gmem3_0_ARSIZE = 3'd0;

assign m_axi_gmem3_0_ARUSER = 1'd0;

assign m_axi_gmem3_0_ARVALID = 1'b0;

assign m_axi_gmem3_0_AWADDR = sext_ln130_1_fu_459_p1;

assign m_axi_gmem3_0_AWBURST = 2'd0;

assign m_axi_gmem3_0_AWCACHE = 4'd0;

assign m_axi_gmem3_0_AWID = 1'd0;

assign m_axi_gmem3_0_AWLEN = 64'd1;

assign m_axi_gmem3_0_AWLOCK = 2'd0;

assign m_axi_gmem3_0_AWPROT = 3'd0;

assign m_axi_gmem3_0_AWQOS = 4'd0;

assign m_axi_gmem3_0_AWREGION = 4'd0;

assign m_axi_gmem3_0_AWSIZE = 3'd0;

assign m_axi_gmem3_0_AWUSER = 1'd0;

assign m_axi_gmem3_0_RREADY = 1'b0;

assign m_axi_gmem3_0_WDATA = AB_stream_read_reg_555;

assign m_axi_gmem3_0_WID = 1'd0;

assign m_axi_gmem3_0_WLAST = 1'b0;

assign m_axi_gmem3_0_WSTRB = 64'd18446744073709551615;

assign m_axi_gmem3_0_WUSER = 1'd0;

assign mul1_fu_369_p3 = {{select_ln123_1_fu_362_p3}, {4'd0}};

assign mul_fu_295_p3 = {{select_ln125_1_fu_287_p3}, {4'd0}};

assign or_ln125_fu_273_p2 = (icmp_ln125_fu_236_p2 | and_ln123_fu_261_p2);

assign select_ln123_1_fu_362_p3 = ((icmp_ln125_reg_528_pp0_iter2_reg[0:0] == 1'b1) ? add_ln123_1_fu_356_p2 : ib_fu_122);

assign select_ln123_fu_241_p3 = ((icmp_ln125_fu_236_p2[0:0] == 1'b1) ? 28'd0 : jb_fu_114);

assign select_ln125_1_fu_287_p3 = ((and_ln123_fu_261_p2[0:0] == 1'b1) ? jb_2_fu_267_p2 : select_ln123_fu_241_p3);

assign select_ln125_2_fu_325_p3 = ((icmp_ln125_fu_236_p2[0:0] == 1'b1) ? 34'd1 : add_ln125_1_fu_319_p2);

assign select_ln125_fu_279_p3 = ((or_ln125_fu_273_p2[0:0] == 1'b1) ? 5'd0 : j_fu_110);

assign select_ln130_fu_424_p3 = ((tmp_fu_387_p3[0:0] == 1'b1) ? sub_ln130_1_fu_409_p2 : tmp_6_fu_415_p4);

assign sext_ln130_1_fu_459_p1 = $signed(trunc_ln130_1_reg_550);

assign sext_ln130_fu_440_p1 = $signed(shl_ln_fu_432_p3);

assign shl_ln_fu_432_p3 = {{select_ln130_fu_424_p3}, {6'd0}};

assign sub_ln130_1_fu_409_p2 = (28'd0 - tmp_5_fu_399_p4);

assign sub_ln130_fu_394_p2 = (32'd0 - add_ln130_1_reg_543);

assign tmp_5_fu_399_p4 = {{sub_ln130_fu_394_p2[31:4]}};

assign tmp_6_fu_415_p4 = {{add_ln130_1_reg_543[31:4]}};

assign tmp_fu_387_p3 = add_ln130_1_reg_543[32'd31];

assign xor_ln123_fu_249_p2 = (icmp_ln125_fu_236_p2 ^ 1'd1);

assign zext_ln127_fu_303_p1 = select_ln125_fu_279_p3;

always @ (posedge ap_clk) begin
    bound_reg_519[33:31] <= 3'b000;
end

endmodule //MM_writeTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_j_output_loop
