[hls]
relative_roots=Z:/Labs/clab/baseline_blockedMM
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=readattiles/k_BLOCK_loop  
syn.directive.loop_flatten=readattiles/j_BLOCK_loop  
syn.directive.loop_flatten=readattiles/i_BLOCK_loop  
syn.directive.loop_flatten=readbtiles/k_BLOCK_loop  
syn.directive.loop_flatten=readbtiles/j_BLOCK_loop  
syn.directive.loop_flatten=readbtiles/i_BLOCK_loop  
syn.directive.loop_flatten=computetiles/k_loop  
syn.directive.loop_flatten=computetiles/k_BLOCK_loop  
syn.directive.loop_flatten=writetiles/j_BLOCK_loop  
syn.directive.loop_flatten=writetiles/i_BLOCK_loop  


