// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module MM_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        A_stream_din,
        A_stream_full_n,
        A_stream_write,
        A_stream_num_data_valid,
        A_stream_fifo_cap,
        bound25,
        bound6,
        smax,
        bound,
        N,
        AT
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [511:0] m_axi_gmem0_0_WDATA;
output  [63:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [511:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
output  [511:0] A_stream_din;
input   A_stream_full_n;
output   A_stream_write;
input  [5:0] A_stream_num_data_valid;
input  [5:0] A_stream_fifo_cap;
input  [84:0] bound25;
input  [57:0] bound6;
input  [26:0] smax;
input  [30:0] bound;
input  [31:0] N;
input  [63:0] AT;

reg ap_idle;
reg m_axi_gmem0_0_ARVALID;
reg m_axi_gmem0_0_RREADY;
reg A_stream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln12_fu_238_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem0_blk_n_R;
reg    A_stream_blk_n;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [33:0] bound_cast_fu_197_p1;
reg   [33:0] bound_cast_reg_612;
wire   [62:0] bound6_cast_fu_201_p1;
reg   [62:0] bound6_cast_reg_617;
wire   [0:0] icmp_ln14_fu_255_p2;
reg   [0:0] icmp_ln14_reg_626;
reg   [0:0] icmp_ln14_reg_626_pp0_iter2_reg;
reg   [0:0] icmp_ln14_reg_626_pp0_iter3_reg;
wire   [0:0] select_ln12_fu_270_p3;
reg   [0:0] select_ln12_reg_633;
wire   [0:0] or_ln14_fu_278_p2;
reg   [0:0] or_ln14_reg_639;
wire  signed [31:0] add_ln20_fu_412_p2;
reg  signed [31:0] add_ln20_reg_644;
wire   [31:0] mul_ln20_fu_193_p2;
reg   [31:0] mul_ln20_reg_649;
wire   [31:0] add_ln20_1_fu_458_p2;
reg   [31:0] add_ln20_1_reg_654;
reg   [57:0] trunc_ln20_1_reg_661;
reg   [511:0] gmem0_addr_read_reg_672;
wire  signed [63:0] sext_ln20_1_fu_540_p1;
reg   [4:0] k_01_fu_114;
wire   [4:0] k_fu_418_p2;
wire    ap_loop_init;
reg   [27:0] kb_fu_118;
wire   [27:0] select_ln16_1_fu_392_p3;
reg   [33:0] indvar_flatten_fu_122;
wire   [33:0] select_ln16_2_fu_290_p3;
wire    ap_block_pp0_stage0;
reg   [62:0] indvar_flatten17_fu_126;
wire   [62:0] select_ln14_1_fu_304_p3;
reg   [27:0] ib_fu_130;
wire   [27:0] select_ln12_1_fu_443_p3;
reg   [84:0] indvar_flatten49_fu_134;
wire   [84:0] add_ln12_fu_249_p2;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] icmp_ln16_fu_260_p2;
wire   [0:0] icmp_ln16_1_fu_265_p2;
wire   [33:0] add_ln16_1_fu_284_p2;
wire   [62:0] add_ln14_fu_298_p2;
wire   [0:0] xor_ln14_fu_351_p2;
wire   [0:0] xor_ln12_fu_333_p2;
wire   [0:0] and_ln12_fu_356_p2;
wire   [0:0] icmp_ln18_fu_338_p2;
wire   [27:0] select_ln14_fu_344_p3;
wire   [0:0] and_ln14_fu_362_p2;
wire   [0:0] or_ln16_fu_374_p2;
wire   [0:0] or_ln16_1_fu_379_p2;
wire   [27:0] kb_4_fu_368_p2;
wire   [4:0] select_ln16_fu_384_p3;
wire   [31:0] shl_ln20_1_fu_400_p3;
wire   [31:0] zext_ln18_fu_408_p1;
wire   [27:0] add_ln12_1_fu_437_p2;
wire   [31:0] shl_ln_fu_450_p3;
wire   [31:0] sub_ln20_fu_475_p2;
wire   [27:0] tmp_s_fu_480_p4;
wire   [0:0] tmp_fu_468_p3;
wire   [27:0] sub_ln20_1_fu_490_p2;
wire   [27:0] tmp_4_fu_496_p4;
wire   [27:0] select_ln20_fu_505_p3;
wire   [33:0] shl_ln20_2_fu_513_p3;
wire  signed [63:0] sext_ln20_fu_521_p1;
wire   [63:0] add_ln20_2_fu_525_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 k_01_fu_114 = 5'd0;
#0 kb_fu_118 = 28'd0;
#0 indvar_flatten_fu_122 = 34'd0;
#0 indvar_flatten17_fu_126 = 63'd0;
#0 ib_fu_130 = 28'd0;
#0 indvar_flatten49_fu_134 = 85'd0;
#0 ap_done_reg = 1'b0;
end

MM_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U3(
    .din0(add_ln20_reg_644),
    .din1(N),
    .dout(mul_ln20_fu_193_p2)
);

MM_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ib_fu_130 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            ib_fu_130 <= select_ln12_1_fu_443_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten17_fu_126 <= 63'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln12_fu_238_p2 == 1'd0))) begin
            indvar_flatten17_fu_126 <= select_ln14_1_fu_304_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten49_fu_134 <= 85'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln12_fu_238_p2 == 1'd0))) begin
            indvar_flatten49_fu_134 <= add_ln12_fu_249_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_122 <= 34'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln12_fu_238_p2 == 1'd0))) begin
            indvar_flatten_fu_122 <= select_ln16_2_fu_290_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            k_01_fu_114 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            k_01_fu_114 <= k_fu_418_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            kb_fu_118 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            kb_fu_118 <= select_ln16_1_fu_392_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln20_1_reg_654 <= add_ln20_1_fu_458_p2;
        add_ln20_reg_644 <= add_ln20_fu_412_p2;
        gmem0_addr_read_reg_672 <= m_axi_gmem0_0_RDATA;
        mul_ln20_reg_649 <= mul_ln20_fu_193_p2;
        trunc_ln20_1_reg_661 <= {{add_ln20_2_fu_525_p2[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln14_reg_626_pp0_iter2_reg <= icmp_ln14_reg_626;
        icmp_ln14_reg_626_pp0_iter3_reg <= icmp_ln14_reg_626_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        bound6_cast_reg_617[57 : 0] <= bound6_cast_fu_201_p1[57 : 0];
        bound_cast_reg_612[30 : 0] <= bound_cast_fu_197_p1[30 : 0];
        icmp_ln14_reg_626 <= icmp_ln14_fu_255_p2;
        or_ln14_reg_639 <= or_ln14_fu_278_p2;
        select_ln12_reg_633 <= select_ln12_fu_270_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        A_stream_blk_n = A_stream_full_n;
    end else begin
        A_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        A_stream_write = 1'b1;
    end else begin
        A_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln12_fu_238_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter14_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_stream_din = gmem0_addr_read_reg_672;

assign add_ln12_1_fu_437_p2 = (ib_fu_130 + 28'd1);

assign add_ln12_fu_249_p2 = (indvar_flatten49_fu_134 + 85'd1);

assign add_ln14_fu_298_p2 = (indvar_flatten17_fu_126 + 63'd1);

assign add_ln16_1_fu_284_p2 = (indvar_flatten_fu_122 + 34'd1);

assign add_ln20_1_fu_458_p2 = (mul_ln20_reg_649 + shl_ln_fu_450_p3);

assign add_ln20_2_fu_525_p2 = ($signed(sext_ln20_fu_521_p1) + $signed(AT));

assign add_ln20_fu_412_p2 = (shl_ln20_1_fu_400_p3 + zext_ln18_fu_408_p1);

assign and_ln12_fu_356_p2 = (xor_ln14_fu_351_p2 & xor_ln12_fu_333_p2);

assign and_ln14_fu_362_p2 = (icmp_ln18_fu_338_p2 & and_ln12_fu_356_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == A_stream_full_n)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == A_stream_full_n)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == A_stream_full_n)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == A_stream_full_n)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0)) | ((m_axi_gmem0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bound6_cast_fu_201_p1 = bound6;

assign bound_cast_fu_197_p1 = bound;

assign icmp_ln12_fu_238_p2 = ((indvar_flatten49_fu_134 == bound25) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_255_p2 = ((indvar_flatten17_fu_126 == bound6_cast_reg_617) ? 1'b1 : 1'b0);

assign icmp_ln16_1_fu_265_p2 = ((indvar_flatten_fu_122 == bound_cast_reg_612) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_260_p2 = ((smax == 27'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_338_p2 = ((k_01_fu_114 == 5'd16) ? 1'b1 : 1'b0);

assign k_fu_418_p2 = (select_ln16_fu_384_p3 + 5'd1);

assign kb_4_fu_368_p2 = (select_ln14_fu_344_p3 + 28'd1);

assign m_axi_gmem0_0_ARADDR = sext_ln20_1_fu_540_p1;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 64'd1;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 512'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 64'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign or_ln14_fu_278_p2 = (select_ln12_fu_270_p3 | icmp_ln14_fu_255_p2);

assign or_ln16_1_fu_379_p2 = (or_ln16_fu_374_p2 | icmp_ln14_reg_626);

assign or_ln16_fu_374_p2 = (select_ln12_reg_633 | and_ln14_fu_362_p2);

assign select_ln12_1_fu_443_p3 = ((icmp_ln14_reg_626_pp0_iter3_reg[0:0] == 1'b1) ? add_ln12_1_fu_437_p2 : ib_fu_130);

assign select_ln12_fu_270_p3 = ((icmp_ln14_fu_255_p2[0:0] == 1'b1) ? icmp_ln16_fu_260_p2 : icmp_ln16_1_fu_265_p2);

assign select_ln14_1_fu_304_p3 = ((icmp_ln14_fu_255_p2[0:0] == 1'b1) ? 63'd1 : add_ln14_fu_298_p2);

assign select_ln14_fu_344_p3 = ((or_ln14_reg_639[0:0] == 1'b1) ? 28'd0 : kb_fu_118);

assign select_ln16_1_fu_392_p3 = ((and_ln14_fu_362_p2[0:0] == 1'b1) ? kb_4_fu_368_p2 : select_ln14_fu_344_p3);

assign select_ln16_2_fu_290_p3 = ((or_ln14_fu_278_p2[0:0] == 1'b1) ? 34'd1 : add_ln16_1_fu_284_p2);

assign select_ln16_fu_384_p3 = ((or_ln16_1_fu_379_p2[0:0] == 1'b1) ? 5'd0 : k_01_fu_114);

assign select_ln20_fu_505_p3 = ((tmp_fu_468_p3[0:0] == 1'b1) ? sub_ln20_1_fu_490_p2 : tmp_4_fu_496_p4);

assign sext_ln20_1_fu_540_p1 = $signed(trunc_ln20_1_reg_661);

assign sext_ln20_fu_521_p1 = $signed(shl_ln20_2_fu_513_p3);

assign shl_ln20_1_fu_400_p3 = {{select_ln16_1_fu_392_p3}, {4'd0}};

assign shl_ln20_2_fu_513_p3 = {{select_ln20_fu_505_p3}, {6'd0}};

assign shl_ln_fu_450_p3 = {{select_ln12_1_fu_443_p3}, {4'd0}};

assign sub_ln20_1_fu_490_p2 = (28'd0 - tmp_s_fu_480_p4);

assign sub_ln20_fu_475_p2 = (32'd0 - add_ln20_1_reg_654);

assign tmp_4_fu_496_p4 = {{add_ln20_1_reg_654[31:4]}};

assign tmp_fu_468_p3 = add_ln20_1_reg_654[32'd31];

assign tmp_s_fu_480_p4 = {{sub_ln20_fu_475_p2[31:4]}};

assign xor_ln12_fu_333_p2 = (icmp_ln14_reg_626 ^ 1'd1);

assign xor_ln14_fu_351_p2 = (select_ln12_reg_633 ^ 1'd1);

assign zext_ln18_fu_408_p1 = select_ln16_fu_384_p3;

always @ (posedge ap_clk) begin
    bound_cast_reg_612[33:31] <= 3'b000;
    bound6_cast_reg_617[62:58] <= 5'b00000;
end

endmodule //MM_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop
