// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module MM_readAtTiles (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        AT,
        A_stream_din,
        A_stream_full_n,
        A_stream_write,
        A_stream_num_data_valid,
        A_stream_fifo_cap,
        N,
        M,
        P
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [511:0] m_axi_gmem0_0_WDATA;
output  [63:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [511:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [8:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] AT;
output  [511:0] A_stream_din;
input   A_stream_full_n;
output   A_stream_write;
input  [5:0] A_stream_num_data_valid;
input  [5:0] A_stream_fifo_cap;
input  [31:0] N;
input  [31:0] M;
input  [31:0] P;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [26:0] smax_fu_213_p3;
reg   [26:0] smax_reg_325;
reg    ap_block_state1;
wire   [26:0] smax2_fu_227_p3;
reg   [26:0] smax2_reg_331;
reg   [31:0] N_read_reg_336;
wire    ap_CS_fsm_state2;
wire   [30:0] tmp_9_fu_287_p3;
reg   [30:0] tmp_9_reg_341;
wire   [57:0] bound6_fu_95_p2;
reg   [57:0] bound6_reg_346;
wire   [26:0] smax20_fu_309_p3;
reg   [26:0] smax20_reg_352;
wire    ap_CS_fsm_state3;
wire   [84:0] grp_fu_99_p2;
reg   [84:0] bound25_reg_367;
wire    ap_CS_fsm_state4;
reg   [63:0] AT_read_reg_372;
wire    ap_CS_fsm_state5;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_idle;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_ready;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWID;
wire   [31:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWUSER;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WVALID;
wire   [511:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WDATA;
wire   [63:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WSTRB;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WID;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WUSER;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARID;
wire   [31:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARUSER;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_RREADY;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_BREADY;
wire   [511:0] grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_din;
wire    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_write;
reg    grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [26:0] bound6_fu_95_p0;
wire   [30:0] bound6_fu_95_p1;
wire   [26:0] grp_fu_99_p0;
wire   [57:0] grp_fu_99_p1;
wire   [31:0] sub_ln14_fu_111_p2;
wire   [27:0] tmp_5_fu_117_p4;
wire   [0:0] tmp_22_fu_103_p3;
wire   [27:0] sub_ln14_1_fu_127_p2;
wire   [27:0] tmp_6_fu_133_p4;
wire   [27:0] select_ln14_fu_143_p3;
wire   [31:0] sub_ln16_fu_163_p2;
wire   [27:0] tmp_7_fu_169_p4;
wire   [0:0] tmp_23_fu_155_p3;
wire   [27:0] sub_ln16_1_fu_179_p2;
wire   [27:0] tmp_8_fu_185_p4;
wire   [27:0] select_ln16_fu_195_p3;
wire   [0:0] empty_40_fu_207_p2;
wire   [26:0] empty_fu_203_p1;
wire   [0:0] empty_41_fu_221_p2;
wire   [26:0] trunc_ln16_fu_151_p1;
wire   [31:0] sub_ln12_fu_243_p2;
wire   [27:0] tmp_fu_249_p4;
wire   [0:0] tmp_21_fu_235_p3;
wire   [27:0] sub_ln12_1_fu_259_p2;
wire   [27:0] tmp_s_fu_265_p4;
wire   [27:0] select_ln12_fu_275_p3;
wire   [0:0] empty_42_fu_303_p2;
wire   [26:0] trunc_ln14_fu_283_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire   [57:0] bound6_fu_95_p00;
wire   [57:0] bound6_fu_95_p10;
wire   [84:0] grp_fu_99_p00;
wire   [84:0] grp_fu_99_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg = 1'b0;
end

MM_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start),
    .ap_done(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done),
    .ap_idle(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_idle),
    .ap_ready(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(m_axi_gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(m_axi_gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(m_axi_gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(m_axi_gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(m_axi_gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(m_axi_gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(m_axi_gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(m_axi_gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .A_stream_din(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_din),
    .A_stream_full_n(A_stream_full_n),
    .A_stream_write(grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_write),
    .A_stream_num_data_valid(6'd0),
    .A_stream_fifo_cap(6'd0),
    .bound25(bound25_reg_367),
    .bound6(bound6_reg_346),
    .smax(smax_reg_325),
    .bound(tmp_9_reg_341),
    .N(N_read_reg_336),
    .AT(AT_read_reg_372)
);

MM_mul_27ns_31ns_58_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 58 ))
mul_27ns_31ns_58_1_1_U13(
    .din0(bound6_fu_95_p0),
    .din1(bound6_fu_95_p1),
    .dout(bound6_fu_95_p2)
);

MM_mul_27ns_58ns_85_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 58 ),
    .dout_WIDTH( 85 ))
mul_27ns_58ns_85_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_99_p0),
    .din1(grp_fu_99_p1),
    .ce(1'b1),
    .dout(grp_fu_99_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_ready == 1'b1)) begin
            grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        AT_read_reg_372 <= AT;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        N_read_reg_336 <= N;
        bound6_reg_346 <= bound6_fu_95_p2;
        smax20_reg_352 <= smax20_fu_309_p3;
        tmp_9_reg_341[30 : 4] <= tmp_9_fu_287_p3[30 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bound25_reg_367 <= grp_fu_99_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        smax2_reg_331 <= smax2_fu_227_p3;
        smax_reg_325 <= smax_fu_213_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_stream_din = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_din;

assign A_stream_write = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_A_stream_write;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bound6_fu_95_p0 = bound6_fu_95_p00;

assign bound6_fu_95_p00 = smax2_reg_331;

assign bound6_fu_95_p1 = bound6_fu_95_p10;

assign bound6_fu_95_p10 = tmp_9_fu_287_p3;

assign empty_40_fu_207_p2 = (($signed(select_ln16_fu_195_p3) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign empty_41_fu_221_p2 = (($signed(select_ln14_fu_143_p3) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign empty_42_fu_303_p2 = (($signed(select_ln12_fu_275_p3) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign empty_fu_203_p1 = select_ln16_fu_195_p3[26:0];

assign grp_fu_99_p0 = grp_fu_99_p00;

assign grp_fu_99_p00 = smax20_reg_352;

assign grp_fu_99_p1 = grp_fu_99_p10;

assign grp_fu_99_p10 = bound6_reg_346;

assign grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_ap_start_reg;

assign m_axi_gmem0_0_ARADDR = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARADDR;

assign m_axi_gmem0_0_ARBURST = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARBURST;

assign m_axi_gmem0_0_ARCACHE = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARCACHE;

assign m_axi_gmem0_0_ARID = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARID;

assign m_axi_gmem0_0_ARLEN = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLEN;

assign m_axi_gmem0_0_ARLOCK = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARLOCK;

assign m_axi_gmem0_0_ARPROT = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARPROT;

assign m_axi_gmem0_0_ARQOS = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARQOS;

assign m_axi_gmem0_0_ARREGION = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARREGION;

assign m_axi_gmem0_0_ARSIZE = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARSIZE;

assign m_axi_gmem0_0_ARUSER = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARUSER;

assign m_axi_gmem0_0_ARVALID = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_ARVALID;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_RREADY = grp_readAtTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_k_BLOCK_loop_k_loop_fu_80_m_axi_gmem0_0_RREADY;

assign m_axi_gmem0_0_WDATA = 512'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 64'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign select_ln12_fu_275_p3 = ((tmp_21_fu_235_p3[0:0] == 1'b1) ? sub_ln12_1_fu_259_p2 : tmp_s_fu_265_p4);

assign select_ln14_fu_143_p3 = ((tmp_22_fu_103_p3[0:0] == 1'b1) ? sub_ln14_1_fu_127_p2 : tmp_6_fu_133_p4);

assign select_ln16_fu_195_p3 = ((tmp_23_fu_155_p3[0:0] == 1'b1) ? sub_ln16_1_fu_179_p2 : tmp_8_fu_185_p4);

assign smax20_fu_309_p3 = ((empty_42_fu_303_p2[0:0] == 1'b1) ? trunc_ln14_fu_283_p1 : 27'd0);

assign smax2_fu_227_p3 = ((empty_41_fu_221_p2[0:0] == 1'b1) ? trunc_ln16_fu_151_p1 : 27'd0);

assign smax_fu_213_p3 = ((empty_40_fu_207_p2[0:0] == 1'b1) ? empty_fu_203_p1 : 27'd0);

assign sub_ln12_1_fu_259_p2 = (28'd0 - tmp_fu_249_p4);

assign sub_ln12_fu_243_p2 = (32'd0 - N);

assign sub_ln14_1_fu_127_p2 = (28'd0 - tmp_5_fu_117_p4);

assign sub_ln14_fu_111_p2 = (32'd0 - P);

assign sub_ln16_1_fu_179_p2 = (28'd0 - tmp_7_fu_169_p4);

assign sub_ln16_fu_163_p2 = (32'd0 - M);

assign tmp_21_fu_235_p3 = N[32'd31];

assign tmp_22_fu_103_p3 = P[32'd31];

assign tmp_23_fu_155_p3 = M[32'd31];

assign tmp_5_fu_117_p4 = {{sub_ln14_fu_111_p2[31:4]}};

assign tmp_6_fu_133_p4 = {{P[31:4]}};

assign tmp_7_fu_169_p4 = {{sub_ln16_fu_163_p2[31:4]}};

assign tmp_8_fu_185_p4 = {{M[31:4]}};

assign tmp_9_fu_287_p3 = {{smax_reg_325}, {4'd0}};

assign tmp_fu_249_p4 = {{sub_ln12_fu_243_p2[31:4]}};

assign tmp_s_fu_265_p4 = {{N[31:4]}};

assign trunc_ln14_fu_283_p1 = select_ln12_fu_275_p3[26:0];

assign trunc_ln16_fu_151_p1 = select_ln14_fu_143_p3[26:0];

always @ (posedge ap_clk) begin
    tmp_9_reg_341[3:0] <= 4'b0000;
end

endmodule //MM_readAtTiles
