

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "35", "36", "37", "38", "39"],
		"CDFG" : "MM",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem", "Type" : "MAXI", "Direction" : "IO",
				"BlockSignal" : [
					{"Name" : "gmem_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_R", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "AT", "Type" : "None", "Direction" : "I"},
			{"Name" : "B", "Type" : "None", "Direction" : "I"},
			{"Name" : "C", "Type" : "None", "Direction" : "I"},
			{"Name" : "ABC", "Type" : "None", "Direction" : "I"},
			{"Name" : "N", "Type" : "None", "Direction" : "I"},
			{"Name" : "M", "Type" : "None", "Direction" : "I"},
			{"Name" : "P", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "k_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state30", "LastState" : ["ap_ST_fsm_state46"], "QuitState" : ["ap_ST_fsm_state30"], "PreState" : ["ap_ST_fsm_state29"], "PostState" : ["ap_ST_fsm_state29"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "k_BLOCK_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state29", "LastState" : ["ap_ST_fsm_state30"], "QuitState" : ["ap_ST_fsm_state29"], "PreState" : ["ap_ST_fsm_state28"], "PostState" : ["ap_ST_fsm_state47"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "i_output_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state48", "LastState" : ["ap_ST_fsm_state48"], "QuitState" : ["ap_ST_fsm_state48"], "PreState" : ["ap_ST_fsm_state47"], "PostState" : ["ap_ST_fsm_state49"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state48_blk"}},
			{"Name" : "j_output_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state47", "LastState" : ["ap_ST_fsm_state58"], "QuitState" : ["ap_ST_fsm_state47"], "PreState" : ["ap_ST_fsm_state29"], "PostState" : ["ap_ST_fsm_state3"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "j_BLOCK_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state47"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "i_BLOCK_loop", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "58", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883", "Parent" : "0", "Child" : ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34"],
		"CDFG" : "MM_Pipeline_i_loop",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "19", "EstimateLatencyMax" : "19",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "AB_block_15_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_14_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_13_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_12_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_11_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_10_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_9_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_8_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_7_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_6_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_5_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_4_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_3_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_2_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_1_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_0_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_load_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "trunc_ln63_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "AB_block_15_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_14_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_13_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_12_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_11_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_10_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_9_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_8_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_7_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_6_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_5_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_4_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_3_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_2_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_1_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "AB_block_0_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "i_loop", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U1", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U2", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U3", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U4", "Parent" : "1"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U5", "Parent" : "1"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U6", "Parent" : "1"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U7", "Parent" : "1"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U8", "Parent" : "1"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U9", "Parent" : "1"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U10", "Parent" : "1"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U11", "Parent" : "1"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U12", "Parent" : "1"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U13", "Parent" : "1"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U14", "Parent" : "1"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U15", "Parent" : "1"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.mul_32s_32s_32_1_1_U16", "Parent" : "1"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U17", "Parent" : "1"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U18", "Parent" : "1"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U19", "Parent" : "1"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U20", "Parent" : "1"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U21", "Parent" : "1"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U22", "Parent" : "1"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U23", "Parent" : "1"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U24", "Parent" : "1"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U25", "Parent" : "1"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U26", "Parent" : "1"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U27", "Parent" : "1"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U28", "Parent" : "1"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U29", "Parent" : "1"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U30", "Parent" : "1"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U31", "Parent" : "1"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.sparsemux_33_4_32_1_1_U32", "Parent" : "1"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_MM_Pipeline_i_loop_fu_883.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U84", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32s_32s_32_1_1_U85", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_33_4_32_1_1_U86", "Parent" : "0"}]}
