-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Thu Apr  9 18:32:14 2026
-- Host        : jwood_Win_PC running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               z:/Labs/clab/baseline_blockedMM/baseline_blockedMM/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity bd_0_hls_inst_0 is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem0_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem0_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARREADY : in STD_LOGIC;
    m_axi_gmem0_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_ARVALID : out STD_LOGIC;
    m_axi_gmem0_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem0_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWREADY : in STD_LOGIC;
    m_axi_gmem0_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_AWVALID : out STD_LOGIC;
    m_axi_gmem0_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem0_BREADY : out STD_LOGIC;
    m_axi_gmem0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_BVALID : in STD_LOGIC;
    m_axi_gmem0_RDATA : in STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem0_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem0_RLAST : in STD_LOGIC;
    m_axi_gmem0_RREADY : out STD_LOGIC;
    m_axi_gmem0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_RVALID : in STD_LOGIC;
    m_axi_gmem0_WDATA : out STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem0_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem0_WLAST : out STD_LOGIC;
    m_axi_gmem0_WREADY : in STD_LOGIC;
    m_axi_gmem0_WSTRB : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem0_WVALID : out STD_LOGIC;
    m_axi_gmem1_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem1_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARREADY : in STD_LOGIC;
    m_axi_gmem1_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_ARVALID : out STD_LOGIC;
    m_axi_gmem1_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem1_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWREADY : in STD_LOGIC;
    m_axi_gmem1_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_AWVALID : out STD_LOGIC;
    m_axi_gmem1_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem1_BREADY : out STD_LOGIC;
    m_axi_gmem1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_BVALID : in STD_LOGIC;
    m_axi_gmem1_RDATA : in STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem1_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem1_RLAST : in STD_LOGIC;
    m_axi_gmem1_RREADY : out STD_LOGIC;
    m_axi_gmem1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_RVALID : in STD_LOGIC;
    m_axi_gmem1_WDATA : out STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem1_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem1_WLAST : out STD_LOGIC;
    m_axi_gmem1_WREADY : in STD_LOGIC;
    m_axi_gmem1_WSTRB : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem1_WVALID : out STD_LOGIC;
    m_axi_gmem2_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem2_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARREADY : in STD_LOGIC;
    m_axi_gmem2_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_ARVALID : out STD_LOGIC;
    m_axi_gmem2_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem2_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWREADY : in STD_LOGIC;
    m_axi_gmem2_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_AWVALID : out STD_LOGIC;
    m_axi_gmem2_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem2_BREADY : out STD_LOGIC;
    m_axi_gmem2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_BVALID : in STD_LOGIC;
    m_axi_gmem2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem2_RLAST : in STD_LOGIC;
    m_axi_gmem2_RREADY : out STD_LOGIC;
    m_axi_gmem2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_RVALID : in STD_LOGIC;
    m_axi_gmem2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem2_WLAST : out STD_LOGIC;
    m_axi_gmem2_WREADY : in STD_LOGIC;
    m_axi_gmem2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_WVALID : out STD_LOGIC;
    m_axi_gmem3_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem3_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARREADY : in STD_LOGIC;
    m_axi_gmem3_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_ARVALID : out STD_LOGIC;
    m_axi_gmem3_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem3_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWREADY : in STD_LOGIC;
    m_axi_gmem3_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_AWVALID : out STD_LOGIC;
    m_axi_gmem3_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem3_BREADY : out STD_LOGIC;
    m_axi_gmem3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_BVALID : in STD_LOGIC;
    m_axi_gmem3_RDATA : in STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem3_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem3_RLAST : in STD_LOGIC;
    m_axi_gmem3_RREADY : out STD_LOGIC;
    m_axi_gmem3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_RVALID : in STD_LOGIC;
    m_axi_gmem3_WDATA : out STD_LOGIC_VECTOR ( 511 downto 0 );
    m_axi_gmem3_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem3_WLAST : out STD_LOGIC;
    m_axi_gmem3_WREADY : in STD_LOGIC;
    m_axi_gmem3_WSTRB : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem3_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of bd_0_hls_inst_0 : entity is "bd_0_hls_inst_0,MM,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of bd_0_hls_inst_0 : entity is "bd_0_hls_inst_0,MM,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=MM,x_ipVersion=1.0,x_ipCoreRevision=2114558428,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=7,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_GMEM0_ID_WIDTH=1,C_M_AXI_GMEM0_ADDR_WIDTH=64,C_M_AXI_GMEM0_DATA_WIDTH=512,C_M_AXI_GMEM0_AWUSER_WIDTH=1,C_M_AXI_GMEM0_ARUSER_WIDTH=1,C_M_AXI_GMEM0_WUSER_WIDTH=1,C_M_AXI_GMEM0_RUSER_WIDTH=1,C_M_AXI_GMEM0_BUSER_WIDTH=1,C_M_AXI_GMEM0_USER_VALUE=0x00000000,C_M_AXI_GMEM0_PROT_VALUE=000,C_M_AXI_GMEM0_CACHE_VALUE=0011,C_M_AXI_GMEM1_ID_WIDTH=1,C_M_AXI_GMEM1_ADDR_WIDTH=64,C_M_AXI_GMEM1_DATA_WIDTH=512,C_M_AXI_GMEM1_AWUSER_WIDTH=1,C_M_AXI_GMEM1_ARUSER_WIDTH=1,C_M_AXI_GMEM1_WUSER_WIDTH=1,C_M_AXI_GMEM1_RUSER_WIDTH=1,C_M_AXI_GMEM1_BUSER_WIDTH=1,C_M_AXI_GMEM1_USER_VALUE=0x00000000,C_M_AXI_GMEM1_PROT_VALUE=000,C_M_AXI_GMEM1_CACHE_VALUE=0011,C_M_AXI_GMEM2_ID_WIDTH=1,C_M_AXI_GMEM2_ADDR_WIDTH=64,C_M_AXI_GMEM2_DATA_WIDTH=32,C_M_AXI_GMEM2_AWUSER_WIDTH=1,C_M_AXI_GMEM2_ARUSER_WIDTH=1,C_M_AXI_GMEM2_WUSER_WIDTH=1,C_M_AXI_GMEM2_RUSER_WIDTH=1,C_M_AXI_GMEM2_BUSER_WIDTH=1,C_M_AXI_GMEM2_USER_VALUE=0x00000000,C_M_AXI_GMEM2_PROT_VALUE=000,C_M_AXI_GMEM2_CACHE_VALUE=0011,C_M_AXI_GMEM3_ID_WIDTH=1,C_M_AXI_GMEM3_ADDR_WIDTH=64,C_M_AXI_GMEM3_DATA_WIDTH=512,C_M_AXI_GMEM3_AWUSER_WIDTH=1,C_M_AXI_GMEM3_ARUSER_WIDTH=1,C_M_AXI_GMEM3_WUSER_WIDTH=1,C_M_AXI_GMEM3_RUSER_WIDTH=1,C_M_AXI_GMEM3_BUSER_WIDTH=1,C_M_AXI_GMEM3_USER_VALUE=0x00000000,C_M_AXI_GMEM3_PROT_VALUE=000,C_M_AXI_GMEM3_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of bd_0_hls_inst_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of bd_0_hls_inst_0 : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of bd_0_hls_inst_0 : entity is "yes";
end bd_0_hls_inst_0;

architecture stub of bd_0_hls_inst_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[6:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[6:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_gmem0_ARADDR[63:0],m_axi_gmem0_ARBURST[1:0],m_axi_gmem0_ARCACHE[3:0],m_axi_gmem0_ARID[0:0],m_axi_gmem0_ARLEN[7:0],m_axi_gmem0_ARLOCK[1:0],m_axi_gmem0_ARPROT[2:0],m_axi_gmem0_ARQOS[3:0],m_axi_gmem0_ARREADY,m_axi_gmem0_ARREGION[3:0],m_axi_gmem0_ARSIZE[2:0],m_axi_gmem0_ARVALID,m_axi_gmem0_AWADDR[63:0],m_axi_gmem0_AWBURST[1:0],m_axi_gmem0_AWCACHE[3:0],m_axi_gmem0_AWID[0:0],m_axi_gmem0_AWLEN[7:0],m_axi_gmem0_AWLOCK[1:0],m_axi_gmem0_AWPROT[2:0],m_axi_gmem0_AWQOS[3:0],m_axi_gmem0_AWREADY,m_axi_gmem0_AWREGION[3:0],m_axi_gmem0_AWSIZE[2:0],m_axi_gmem0_AWVALID,m_axi_gmem0_BID[0:0],m_axi_gmem0_BREADY,m_axi_gmem0_BRESP[1:0],m_axi_gmem0_BVALID,m_axi_gmem0_RDATA[511:0],m_axi_gmem0_RID[0:0],m_axi_gmem0_RLAST,m_axi_gmem0_RREADY,m_axi_gmem0_RRESP[1:0],m_axi_gmem0_RVALID,m_axi_gmem0_WDATA[511:0],m_axi_gmem0_WID[0:0],m_axi_gmem0_WLAST,m_axi_gmem0_WREADY,m_axi_gmem0_WSTRB[63:0],m_axi_gmem0_WVALID,m_axi_gmem1_ARADDR[63:0],m_axi_gmem1_ARBURST[1:0],m_axi_gmem1_ARCACHE[3:0],m_axi_gmem1_ARID[0:0],m_axi_gmem1_ARLEN[7:0],m_axi_gmem1_ARLOCK[1:0],m_axi_gmem1_ARPROT[2:0],m_axi_gmem1_ARQOS[3:0],m_axi_gmem1_ARREADY,m_axi_gmem1_ARREGION[3:0],m_axi_gmem1_ARSIZE[2:0],m_axi_gmem1_ARVALID,m_axi_gmem1_AWADDR[63:0],m_axi_gmem1_AWBURST[1:0],m_axi_gmem1_AWCACHE[3:0],m_axi_gmem1_AWID[0:0],m_axi_gmem1_AWLEN[7:0],m_axi_gmem1_AWLOCK[1:0],m_axi_gmem1_AWPROT[2:0],m_axi_gmem1_AWQOS[3:0],m_axi_gmem1_AWREADY,m_axi_gmem1_AWREGION[3:0],m_axi_gmem1_AWSIZE[2:0],m_axi_gmem1_AWVALID,m_axi_gmem1_BID[0:0],m_axi_gmem1_BREADY,m_axi_gmem1_BRESP[1:0],m_axi_gmem1_BVALID,m_axi_gmem1_RDATA[511:0],m_axi_gmem1_RID[0:0],m_axi_gmem1_RLAST,m_axi_gmem1_RREADY,m_axi_gmem1_RRESP[1:0],m_axi_gmem1_RVALID,m_axi_gmem1_WDATA[511:0],m_axi_gmem1_WID[0:0],m_axi_gmem1_WLAST,m_axi_gmem1_WREADY,m_axi_gmem1_WSTRB[63:0],m_axi_gmem1_WVALID,m_axi_gmem2_ARADDR[63:0],m_axi_gmem2_ARBURST[1:0],m_axi_gmem2_ARCACHE[3:0],m_axi_gmem2_ARID[0:0],m_axi_gmem2_ARLEN[7:0],m_axi_gmem2_ARLOCK[1:0],m_axi_gmem2_ARPROT[2:0],m_axi_gmem2_ARQOS[3:0],m_axi_gmem2_ARREADY,m_axi_gmem2_ARREGION[3:0],m_axi_gmem2_ARSIZE[2:0],m_axi_gmem2_ARVALID,m_axi_gmem2_AWADDR[63:0],m_axi_gmem2_AWBURST[1:0],m_axi_gmem2_AWCACHE[3:0],m_axi_gmem2_AWID[0:0],m_axi_gmem2_AWLEN[7:0],m_axi_gmem2_AWLOCK[1:0],m_axi_gmem2_AWPROT[2:0],m_axi_gmem2_AWQOS[3:0],m_axi_gmem2_AWREADY,m_axi_gmem2_AWREGION[3:0],m_axi_gmem2_AWSIZE[2:0],m_axi_gmem2_AWVALID,m_axi_gmem2_BID[0:0],m_axi_gmem2_BREADY,m_axi_gmem2_BRESP[1:0],m_axi_gmem2_BVALID,m_axi_gmem2_RDATA[31:0],m_axi_gmem2_RID[0:0],m_axi_gmem2_RLAST,m_axi_gmem2_RREADY,m_axi_gmem2_RRESP[1:0],m_axi_gmem2_RVALID,m_axi_gmem2_WDATA[31:0],m_axi_gmem2_WID[0:0],m_axi_gmem2_WLAST,m_axi_gmem2_WREADY,m_axi_gmem2_WSTRB[3:0],m_axi_gmem2_WVALID,m_axi_gmem3_ARADDR[63:0],m_axi_gmem3_ARBURST[1:0],m_axi_gmem3_ARCACHE[3:0],m_axi_gmem3_ARID[0:0],m_axi_gmem3_ARLEN[7:0],m_axi_gmem3_ARLOCK[1:0],m_axi_gmem3_ARPROT[2:0],m_axi_gmem3_ARQOS[3:0],m_axi_gmem3_ARREADY,m_axi_gmem3_ARREGION[3:0],m_axi_gmem3_ARSIZE[2:0],m_axi_gmem3_ARVALID,m_axi_gmem3_AWADDR[63:0],m_axi_gmem3_AWBURST[1:0],m_axi_gmem3_AWCACHE[3:0],m_axi_gmem3_AWID[0:0],m_axi_gmem3_AWLEN[7:0],m_axi_gmem3_AWLOCK[1:0],m_axi_gmem3_AWPROT[2:0],m_axi_gmem3_AWQOS[3:0],m_axi_gmem3_AWREADY,m_axi_gmem3_AWREGION[3:0],m_axi_gmem3_AWSIZE[2:0],m_axi_gmem3_AWVALID,m_axi_gmem3_BID[0:0],m_axi_gmem3_BREADY,m_axi_gmem3_BRESP[1:0],m_axi_gmem3_BVALID,m_axi_gmem3_RDATA[511:0],m_axi_gmem3_RID[0:0],m_axi_gmem3_RLAST,m_axi_gmem3_RREADY,m_axi_gmem3_RRESP[1:0],m_axi_gmem3_RVALID,m_axi_gmem3_WDATA[511:0],m_axi_gmem3_WID[0:0],m_axi_gmem3_WLAST,m_axi_gmem3_WREADY,m_axi_gmem3_WSTRB[63:0],m_axi_gmem3_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 7, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 66000000.0, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_gmem0:m_axi_gmem1:m_axi_gmem2:m_axi_gmem3, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 66000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem0_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem0_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem0, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 512, FREQ_HZ 66000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem0_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem0_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem0_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem0_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem0_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem0_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem0 WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem1_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem1_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem1, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 512, FREQ_HZ 66000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem1_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem1_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem1_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem1_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem1_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem1_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem1 WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem2_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem2_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem2, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 66000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem2_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem2_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem2_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem2_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem2_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem2_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem2 WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem3_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem3_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem3, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 512, FREQ_HZ 66000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem3_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem3_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 BID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem3_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem3_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem3_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WID";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem3_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem3 WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "MM,Vivado 2025.2";
begin
end;
