// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MM_MM,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=901840001,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=3679,HLS_SYN_LUT=3800,HLS_VERSION=2025_1}" *)

module MM (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 48'd1;
parameter    ap_ST_fsm_state2 = 48'd2;
parameter    ap_ST_fsm_state3 = 48'd4;
parameter    ap_ST_fsm_state4 = 48'd8;
parameter    ap_ST_fsm_state5 = 48'd16;
parameter    ap_ST_fsm_state6 = 48'd32;
parameter    ap_ST_fsm_state7 = 48'd64;
parameter    ap_ST_fsm_state8 = 48'd128;
parameter    ap_ST_fsm_state9 = 48'd256;
parameter    ap_ST_fsm_state10 = 48'd512;
parameter    ap_ST_fsm_state11 = 48'd1024;
parameter    ap_ST_fsm_state12 = 48'd2048;
parameter    ap_ST_fsm_state13 = 48'd4096;
parameter    ap_ST_fsm_state14 = 48'd8192;
parameter    ap_ST_fsm_state15 = 48'd16384;
parameter    ap_ST_fsm_state16 = 48'd32768;
parameter    ap_ST_fsm_state17 = 48'd65536;
parameter    ap_ST_fsm_state18 = 48'd131072;
parameter    ap_ST_fsm_state19 = 48'd262144;
parameter    ap_ST_fsm_state20 = 48'd524288;
parameter    ap_ST_fsm_state21 = 48'd1048576;
parameter    ap_ST_fsm_state22 = 48'd2097152;
parameter    ap_ST_fsm_state23 = 48'd4194304;
parameter    ap_ST_fsm_state24 = 48'd8388608;
parameter    ap_ST_fsm_state25 = 48'd16777216;
parameter    ap_ST_fsm_state26 = 48'd33554432;
parameter    ap_ST_fsm_state27 = 48'd67108864;
parameter    ap_ST_fsm_state28 = 48'd134217728;
parameter    ap_ST_fsm_state29 = 48'd268435456;
parameter    ap_ST_fsm_state30 = 48'd536870912;
parameter    ap_ST_fsm_state31 = 48'd1073741824;
parameter    ap_ST_fsm_state32 = 48'd2147483648;
parameter    ap_ST_fsm_state33 = 48'd4294967296;
parameter    ap_ST_fsm_state34 = 48'd8589934592;
parameter    ap_ST_fsm_state35 = 48'd17179869184;
parameter    ap_ST_fsm_state36 = 48'd34359738368;
parameter    ap_ST_fsm_state37 = 48'd68719476736;
parameter    ap_ST_fsm_state38 = 48'd137438953472;
parameter    ap_ST_fsm_state39 = 48'd274877906944;
parameter    ap_ST_fsm_state40 = 48'd549755813888;
parameter    ap_ST_fsm_state41 = 48'd1099511627776;
parameter    ap_ST_fsm_state42 = 48'd2199023255552;
parameter    ap_ST_fsm_state43 = 48'd4398046511104;
parameter    ap_ST_fsm_state44 = 48'd8796093022208;
parameter    ap_ST_fsm_state45 = 48'd17592186044416;
parameter    ap_ST_fsm_state46 = 48'd35184372088832;
parameter    ap_ST_fsm_state47 = 48'd70368744177664;
parameter    ap_ST_fsm_state48 = 48'd140737488355328;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [47:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] A;
wire   [63:0] B;
wire   [63:0] C;
wire   [63:0] ABC;
wire   [31:0] N;
wire   [31:0] M;
wire   [31:0] P;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state4;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state31;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state40;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state43;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state48;
reg  signed [31:0] reg_463;
reg   [31:0] reg_469;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state42;
reg   [63:0] ABC_read_reg_1167;
reg   [63:0] C_read_reg_1172;
reg   [63:0] B_read_reg_1177;
reg   [63:0] A_read_reg_1182;
wire   [27:0] div_fu_514_p3;
reg   [27:0] div_reg_1187;
wire   [27:0] div2_fu_562_p3;
reg   [27:0] div2_reg_1192;
wire   [27:0] div22_fu_610_p3;
reg   [27:0] div22_reg_1197;
wire  signed [35:0] sext_ln34_fu_618_p1;
reg  signed [35:0] sext_ln34_reg_1202;
wire  signed [61:0] sext_ln34_1_fu_622_p1;
reg  signed [61:0] sext_ln34_1_reg_1208;
wire  signed [57:0] sext_ln34_2_fu_626_p1;
reg  signed [57:0] sext_ln34_2_reg_1213;
wire   [57:0] add_ln34_1_fu_646_p2;
reg   [57:0] add_ln34_1_reg_1219;
wire    ap_CS_fsm_state2;
wire   [26:0] add_ln34_fu_660_p2;
reg   [26:0] add_ln34_reg_1227;
wire   [61:0] tmp_6_fu_666_p3;
reg   [61:0] tmp_6_reg_1232;
wire   [31:0] tmp_8_cast_fu_699_p1;
reg   [31:0] tmp_8_cast_reg_1237;
reg   [63:0] gmem_addr_reg_1242;
wire   [26:0] add_ln37_fu_732_p2;
reg   [26:0] add_ln37_reg_1251;
wire    ap_CS_fsm_state3;
wire   [4:0] add_ln42_fu_752_p2;
reg   [4:0] add_ln42_reg_1259;
wire    ap_CS_fsm_state12;
wire   [3:0] trunc_ln42_fu_758_p1;
reg   [3:0] trunc_ln42_reg_1264;
wire   [35:0] zext_ln51_fu_770_p1;
reg   [35:0] zext_ln51_reg_1269;
wire   [61:0] zext_ln51_1_fu_774_p1;
reg   [61:0] zext_ln51_1_reg_1274;
wire   [7:0] tmp_9_fu_778_p3;
reg   [7:0] tmp_9_reg_1279;
wire   [4:0] add_ln44_fu_791_p2;
wire    ap_CS_fsm_state14;
wire   [57:0] add_ln51_1_fu_811_p2;
reg   [57:0] add_ln51_1_reg_1292;
wire    ap_CS_fsm_state15;
wire   [26:0] add_ln51_fu_825_p2;
reg   [26:0] add_ln51_reg_1300;
wire   [61:0] tmp_s_fu_831_p3;
reg   [61:0] tmp_s_reg_1305;
wire   [61:0] zext_ln54_fu_847_p1;
reg   [61:0] zext_ln54_reg_1310;
wire   [4:0] add_ln54_fu_857_p2;
reg   [4:0] add_ln54_reg_1318;
wire    ap_CS_fsm_state16;
wire   [3:0] trunc_ln54_fu_863_p1;
reg   [3:0] trunc_ln54_reg_1323;
wire   [31:0] empty_54_fu_871_p2;
reg   [31:0] empty_54_reg_1328;
wire    ap_CS_fsm_state17;
wire   [61:0] grp_fu_455_p2;
reg   [61:0] empty_55_reg_1338;
wire    ap_CS_fsm_state18;
wire   [7:0] tmp_11_fu_880_p3;
reg   [7:0] tmp_11_reg_1343;
wire    ap_CS_fsm_state19;
wire   [61:0] add_ln59_fu_887_p2;
reg   [61:0] add_ln59_reg_1348;
wire   [35:0] add_ln56_1_fu_891_p2;
reg   [35:0] add_ln56_1_reg_1353;
wire    ap_CS_fsm_state20;
wire   [4:0] add_ln56_fu_902_p2;
reg   [4:0] add_ln56_reg_1361;
wire   [61:0] add_ln59_5_fu_917_p2;
reg   [61:0] add_ln59_5_reg_1366;
reg   [63:0] gmem_addr_2_reg_1371;
reg   [63:0] gmem_addr_3_reg_1377;
wire   [4:0] add_ln62_fu_1006_p2;
reg   [4:0] add_ln62_reg_1386;
wire    ap_CS_fsm_state30;
reg   [31:0] gmem_addr_3_read_reg_1391;
wire   [4:0] add_ln68_fu_1023_p2;
reg   [4:0] add_ln68_reg_1399;
wire    ap_CS_fsm_state33;
wire   [7:0] add_ln70_1_fu_1038_p2;
reg   [7:0] add_ln70_1_reg_1404;
reg  signed [31:0] B_line_load_reg_1414;
wire    ap_CS_fsm_state34;
reg   [7:0] AB_block_addr_2_reg_1419;
wire    ap_CS_fsm_state35;
wire   [31:0] grp_fu_459_p2;
reg   [31:0] mul_ln70_reg_1424;
wire   [35:0] add_ln77_1_fu_1053_p2;
reg   [35:0] add_ln77_1_reg_1429;
wire    ap_CS_fsm_state38;
wire   [4:0] add_ln77_fu_1064_p2;
reg   [4:0] add_ln77_reg_1437;
wire   [3:0] trunc_ln77_fu_1070_p1;
reg   [3:0] trunc_ln77_reg_1442;
wire   [61:0] empty_57_fu_1083_p2;
reg   [61:0] empty_57_reg_1447;
reg   [63:0] gmem_addr_1_reg_1452;
wire    ap_CS_fsm_state39;
wire   [7:0] tmp_12_fu_1120_p3;
reg   [7:0] tmp_12_reg_1459;
wire   [4:0] add_ln79_fu_1133_p2;
reg   [4:0] add_ln79_reg_1467;
wire    ap_CS_fsm_state41;
wire   [31:0] AB_block_q0;
wire   [31:0] B_line_q0;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
wire   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
reg   [63:0] gmem_0_ARADDR;
reg   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg   [26:0] jb_reg_310;
wire   [0:0] icmp_ln34_fu_655_p2;
wire   [0:0] icmp_ln77_fu_1058_p2;
reg   [4:0] i_reg_322;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln44_fu_785_p2;
reg   [4:0] j_reg_333;
reg   [26:0] kb_reg_344;
wire   [0:0] icmp_ln42_fu_746_p2;
wire   [0:0] icmp_ln54_fu_851_p2;
reg   [57:0] phi_mul2_reg_355;
reg   [4:0] i_1_reg_366;
wire   [0:0] icmp_ln51_fu_820_p2;
wire   [0:0] icmp_ln56_fu_896_p2;
reg   [4:0] k_reg_377;
wire   [0:0] icmp_ln68_fu_1017_p2;
reg   [35:0] phi_mul_reg_388;
reg   [4:0] j_2_reg_399;
wire    ap_CS_fsm_state32;
reg   [4:0] j_3_reg_411;
wire    ap_CS_fsm_state37;
wire   [0:0] icmp_ln62_fu_1000_p2;
reg   [4:0] i_2_reg_422;
reg  signed [35:0] phi_mul5_reg_433;
reg   [4:0] j_1_reg_444;
wire   [63:0] zext_ln46_1_fu_806_p1;
wire   [63:0] zext_ln62_fu_1012_p1;
wire   [63:0] zext_ln68_fu_1029_p1;
wire   [63:0] zext_ln70_1_fu_1043_p1;
wire   [63:0] zext_ln81_1_fu_1148_p1;
wire   [0:0] icmp_ln79_fu_1127_p2;
wire  signed [63:0] p_cast5_cast_fu_713_p1;
wire  signed [63:0] sext_ln59_fu_958_p1;
wire  signed [63:0] sext_ln62_fu_990_p1;
wire  signed [63:0] sext_ln79_fu_1110_p1;
reg   [57:0] phi_mul8_fu_172;
wire   [0:0] icmp_ln37_fu_727_p2;
reg   [26:0] ib_fu_176;
reg    AB_block_we0_local;
reg   [31:0] AB_block_d0_local;
reg    AB_block_ce0_local;
reg   [7:0] AB_block_address0_local;
wire   [31:0] add_ln70_fu_1047_p2;
reg    B_line_we0_local;
reg    B_line_ce0_local;
reg   [3:0] B_line_address0_local;
wire   [31:0] grp_fu_455_p0;
wire  signed [31:0] grp_fu_455_p1;
wire   [31:0] p_neg9_fu_482_p2;
wire   [27:0] tmp_fu_488_p4;
wire   [0:0] tmp_15_fu_474_p3;
wire   [27:0] p_neg_t11_fu_498_p2;
wire   [27:0] tmp_1_fu_504_p4;
wire  signed [31:0] tmp_16_fu_522_p1;
wire  signed [31:0] p_neg3_fu_530_p1;
wire   [31:0] p_neg3_fu_530_p2;
wire   [27:0] tmp_2_fu_536_p4;
wire  signed [31:0] tmp_3_fu_552_p1;
wire   [0:0] tmp_16_fu_522_p3;
wire   [27:0] p_neg_t5_fu_546_p2;
wire   [27:0] tmp_3_fu_552_p4;
wire  signed [31:0] tmp_17_fu_570_p1;
wire  signed [31:0] p_neg_fu_578_p1;
wire   [31:0] p_neg_fu_578_p2;
wire   [27:0] tmp_4_fu_584_p4;
wire  signed [31:0] tmp_5_fu_600_p1;
wire   [0:0] tmp_17_fu_570_p3;
wire   [27:0] p_neg_t_fu_594_p2;
wire   [27:0] tmp_5_fu_600_p4;
wire  signed [31:0] sext_ln34_fu_618_p0;
wire  signed [31:0] sext_ln34_1_fu_622_p0;
wire  signed [31:0] sext_ln34_2_fu_626_p0;
wire   [27:0] zext_ln34_fu_651_p1;
wire   [32:0] tmp_7_fu_674_p3;
wire   [63:0] p_cast16_fu_682_p1;
wire   [30:0] tmp_8_fu_691_p3;
wire   [63:0] empty_fu_686_p2;
wire   [61:0] p_cast5_fu_703_p4;
wire   [27:0] zext_ln37_fu_723_p1;
wire   [30:0] shl_ln_fu_762_p3;
wire   [7:0] zext_ln46_fu_797_p1;
wire   [7:0] add_ln46_fu_801_p2;
wire   [27:0] zext_ln51_2_fu_816_p1;
wire   [30:0] tmp_10_fu_839_p3;
wire   [31:0] zext_ln54_1_fu_867_p1;
wire   [35:0] add_ln59_1_fu_908_p2;
wire  signed [61:0] sext_ln59_1_fu_913_p1;
wire   [3:0] trunc_ln59_fu_922_p1;
wire   [61:0] zext_ln59_fu_926_p1;
wire   [61:0] add_ln59_3_fu_930_p2;
wire   [63:0] shl_ln59_1_fu_935_p3;
wire   [63:0] add_ln59_4_fu_943_p2;
wire   [61:0] trunc_ln59_1_fu_948_p4;
wire   [63:0] shl_ln1_fu_968_p3;
wire   [63:0] add_ln59_2_fu_975_p2;
wire   [61:0] trunc_ln2_fu_980_p4;
wire   [7:0] zext_ln70_fu_1034_p1;
wire  signed [61:0] p_cast13_fu_1074_p1;
wire   [61:0] tmp1_fu_1078_p2;
wire   [63:0] tmp_13_fu_1088_p3;
wire   [63:0] empty_58_fu_1095_p2;
wire   [61:0] trunc_ln_fu_1100_p4;
wire   [7:0] zext_ln81_fu_1139_p1;
wire   [7:0] add_ln81_fu_1143_p2;
reg   [47:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
reg    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
reg    ap_ST_fsm_state48_blk;
wire   [61:0] grp_fu_455_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 48'd1;
#0 phi_mul8_fu_172 = 58'd0;
#0 ib_fu_176 = 27'd0;
end

MM_AB_block_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
AB_block_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(AB_block_address0_local),
    .ce0(AB_block_ce0_local),
    .we0(AB_block_we0_local),
    .d0(AB_block_d0_local),
    .q0(AB_block_q0)
);

MM_B_line_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
B_line_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_line_address0_local),
    .ce0(B_line_ce0_local),
    .we0(B_line_we0_local),
    .d0(gmem_addr_3_read_reg_1391),
    .q0(B_line_q0)
);

MM_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A(A),
    .B(B),
    .C(C),
    .ABC(ABC),
    .N(N),
    .M(M),
    .P(P),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MM_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_0_ARADDR),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_addr_1_reg_1452),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(reg_469),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

MM_mul_32ns_32s_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 62 ))
mul_32ns_32s_62_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_455_p0),
    .din1(grp_fu_455_p1),
    .ce(1'b1),
    .dout(grp_fu_455_p2)
);

MM_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(B_line_load_reg_1414),
    .din1(reg_463),
    .ce(1'b1),
    .dout(grp_fu_459_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_896_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        i_1_reg_366 <= add_ln54_reg_1318;
    end else if (((icmp_ln51_fu_820_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        i_1_reg_366 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_820_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        i_2_reg_422 <= 5'd0;
    end else if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state48))) begin
        i_2_reg_422 <= add_ln77_reg_1437;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln44_fu_785_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        i_reg_322 <= add_ln42_reg_1259;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_reg_322 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ib_fu_176 <= 27'd0;
    end else if (((icmp_ln37_fu_727_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ib_fu_176 <= add_ln34_reg_1227;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
        j_1_reg_444 <= add_ln79_reg_1467;
    end else if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
        j_1_reg_444 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        j_2_reg_399 <= add_ln62_reg_1386;
    end else if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
        j_2_reg_399 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln62_fu_1000_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        j_3_reg_411 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        j_3_reg_411 <= add_ln68_reg_1399;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln44_fu_785_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        j_reg_333 <= add_ln44_fu_791_p2;
    end else if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        j_reg_333 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln77_fu_1058_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
        jb_reg_310 <= add_ln37_reg_1251;
    end else if (((icmp_ln34_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        jb_reg_310 <= 27'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_fu_1017_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        k_reg_377 <= add_ln56_reg_1361;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        k_reg_377 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln54_fu_851_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        kb_reg_344 <= add_ln51_reg_1300;
    end else if (((icmp_ln42_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        kb_reg_344 <= 27'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln54_fu_851_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        phi_mul2_reg_355 <= add_ln51_1_reg_1292;
    end else if (((icmp_ln42_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        phi_mul2_reg_355 <= 58'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_820_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        phi_mul5_reg_433 <= 36'd0;
    end else if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state48))) begin
        phi_mul5_reg_433 <= add_ln77_1_reg_1429;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul8_fu_172 <= 58'd0;
    end else if (((icmp_ln37_fu_727_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul8_fu_172 <= add_ln34_1_reg_1219;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_fu_1017_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        phi_mul_reg_388 <= add_ln56_1_reg_1353;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        phi_mul_reg_388 <= 36'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ABC_read_reg_1167 <= ABC;
        A_read_reg_1182 <= A;
        B_read_reg_1177 <= B;
        C_read_reg_1172 <= C;
        div22_reg_1197 <= div22_fu_610_p3;
        div2_reg_1192 <= div2_fu_562_p3;
        div_reg_1187 <= div_fu_514_p3;
        sext_ln34_1_reg_1208 <= sext_ln34_1_fu_622_p1;
        sext_ln34_2_reg_1213 <= sext_ln34_2_fu_626_p1;
        sext_ln34_reg_1202 <= sext_ln34_fu_618_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        AB_block_addr_2_reg_1419 <= zext_ln70_1_fu_1043_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        B_line_load_reg_1414 <= B_line_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln34_1_reg_1219 <= add_ln34_1_fu_646_p2;
        add_ln34_reg_1227 <= add_ln34_fu_660_p2;
        gmem_addr_reg_1242 <= p_cast5_cast_fu_713_p1;
        tmp_6_reg_1232[61 : 4] <= tmp_6_fu_666_p3[61 : 4];
        tmp_8_cast_reg_1237[30 : 4] <= tmp_8_cast_fu_699_p1[30 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln37_reg_1251 <= add_ln37_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln42_reg_1259 <= add_ln42_fu_752_p2;
        trunc_ln42_reg_1264 <= trunc_ln42_fu_758_p1;
        zext_ln51_1_reg_1274[30 : 4] <= zext_ln51_1_fu_774_p1[30 : 4];
        zext_ln51_reg_1269[30 : 4] <= zext_ln51_fu_770_p1[30 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln51_1_reg_1292 <= add_ln51_1_fu_811_p2;
        add_ln51_reg_1300 <= add_ln51_fu_825_p2;
        tmp_s_reg_1305[61 : 4] <= tmp_s_fu_831_p3[61 : 4];
        zext_ln54_reg_1310[30 : 4] <= zext_ln54_fu_847_p1[30 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln54_reg_1318 <= add_ln54_fu_857_p2;
        empty_54_reg_1328 <= empty_54_fu_871_p2;
        trunc_ln54_reg_1323 <= trunc_ln54_fu_863_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        add_ln56_1_reg_1353 <= add_ln56_1_fu_891_p2;
        add_ln56_reg_1361 <= add_ln56_fu_902_p2;
        add_ln59_5_reg_1366 <= add_ln59_5_fu_917_p2;
        gmem_addr_2_reg_1371 <= sext_ln59_fu_958_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln59_reg_1348 <= add_ln59_fu_887_p2;
        tmp_11_reg_1343[7 : 4] <= tmp_11_fu_880_p3[7 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        add_ln62_reg_1386 <= add_ln62_fu_1006_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        add_ln68_reg_1399 <= add_ln68_fu_1023_p2;
        add_ln70_1_reg_1404 <= add_ln70_1_fu_1038_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        add_ln77_1_reg_1429 <= add_ln77_1_fu_1053_p2;
        add_ln77_reg_1437 <= add_ln77_fu_1064_p2;
        empty_57_reg_1447 <= empty_57_fu_1083_p2;
        trunc_ln77_reg_1442 <= trunc_ln77_fu_1070_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        add_ln79_reg_1467 <= add_ln79_fu_1133_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        empty_55_reg_1338 <= grp_fu_455_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        gmem_addr_1_reg_1452 <= sext_ln79_fu_1110_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        gmem_addr_3_read_reg_1391 <= gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        gmem_addr_3_reg_1377 <= sext_ln62_fu_990_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        mul_ln70_reg_1424 <= grp_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_463 <= gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state36))) begin
        reg_469 <= AB_block_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        tmp_12_reg_1459[7 : 4] <= tmp_12_fu_1120_p3[7 : 4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_9_reg_1279[7 : 4] <= tmp_9_fu_778_p3[7 : 4];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        AB_block_address0_local = zext_ln81_1_fu_1148_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        AB_block_address0_local = AB_block_addr_2_reg_1419;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        AB_block_address0_local = zext_ln70_1_fu_1043_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        AB_block_address0_local = zext_ln46_1_fu_806_p1;
    end else begin
        AB_block_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state14))) begin
        AB_block_ce0_local = 1'b1;
    end else begin
        AB_block_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        AB_block_d0_local = add_ln70_fu_1047_p2;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        AB_block_d0_local = reg_463;
    end else begin
        AB_block_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | ((icmp_ln44_fu_785_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14)))) begin
        AB_block_we0_local = 1'b1;
    end else begin
        AB_block_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        B_line_address0_local = zext_ln68_fu_1029_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        B_line_address0_local = zext_ln62_fu_1012_p1;
    end else begin
        B_line_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state33))) begin
        B_line_ce0_local = 1'b1;
    end else begin
        B_line_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        B_line_we0_local = 1'b1;
    end else begin
        B_line_we0_local = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_RVALID == 1'b0)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state43_blk = 1'b1;
    end else begin
        ap_ST_fsm_state43_blk = 1'b0;
    end
end

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state48_blk = 1'b1;
    end else begin
        ap_ST_fsm_state48_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln34_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            gmem_0_ARADDR = gmem_addr_3_reg_1377;
        end else if ((1'b1 == ap_CS_fsm_state21)) begin
            gmem_0_ARADDR = gmem_addr_2_reg_1371;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            gmem_0_ARADDR = gmem_addr_reg_1242;
        end else begin
            gmem_0_ARADDR = 'bx;
        end
    end else begin
        gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        gmem_0_ARLEN = 64'd1;
    end else if ((((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        gmem_0_ARLEN = 64'd16;
    end else begin
        gmem_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22)) | ((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        gmem_0_ARVALID = 1'b1;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
        gmem_0_AWVALID = 1'b1;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state48))) begin
        gmem_0_BREADY = 1'b1;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state31)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29)) | ((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gmem_0_RREADY = 1'b1;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
        gmem_0_WVALID = 1'b1;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state4))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln34_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln37_fu_727_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln42_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln44_fu_785_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln51_fu_820_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln54_fu_851_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln56_fu_896_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((icmp_ln62_fu_1000_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state31 : begin
            if (((gmem_0_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state33 : begin
            if (((icmp_ln68_fu_1017_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state38 : begin
            if (((icmp_ln77_fu_1058_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((icmp_ln79_fu_1127_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state43))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state48))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_1_fu_646_p2 = ($signed(phi_mul8_fu_172) + $signed(sext_ln34_2_reg_1213));

assign add_ln34_fu_660_p2 = (ib_fu_176 + 27'd1);

assign add_ln37_fu_732_p2 = (jb_reg_310 + 27'd1);

assign add_ln42_fu_752_p2 = (i_reg_322 + 5'd1);

assign add_ln44_fu_791_p2 = (j_reg_333 + 5'd1);

assign add_ln46_fu_801_p2 = (tmp_9_reg_1279 + zext_ln46_fu_797_p1);

assign add_ln51_1_fu_811_p2 = ($signed(phi_mul2_reg_355) + $signed(sext_ln34_2_reg_1213));

assign add_ln51_fu_825_p2 = (kb_reg_344 + 27'd1);

assign add_ln54_fu_857_p2 = (i_1_reg_366 + 5'd1);

assign add_ln56_1_fu_891_p2 = ($signed(phi_mul_reg_388) + $signed(sext_ln34_reg_1202));

assign add_ln56_fu_902_p2 = (k_reg_377 + 5'd1);

assign add_ln59_1_fu_908_p2 = (zext_ln51_reg_1269 + phi_mul_reg_388);

assign add_ln59_2_fu_975_p2 = (shl_ln1_fu_968_p3 + B_read_reg_1177);

assign add_ln59_3_fu_930_p2 = (add_ln59_reg_1348 + zext_ln59_fu_926_p1);

assign add_ln59_4_fu_943_p2 = (shl_ln59_1_fu_935_p3 + A_read_reg_1182);

assign add_ln59_5_fu_917_p2 = ($signed(sext_ln59_1_fu_913_p1) + $signed(tmp_s_reg_1305));

assign add_ln59_fu_887_p2 = (empty_55_reg_1338 + zext_ln54_reg_1310);

assign add_ln62_fu_1006_p2 = (j_2_reg_399 + 5'd1);

assign add_ln68_fu_1023_p2 = (j_3_reg_411 + 5'd1);

assign add_ln70_1_fu_1038_p2 = (tmp_11_reg_1343 + zext_ln70_fu_1034_p1);

assign add_ln70_fu_1047_p2 = (reg_469 + mul_ln70_reg_1424);

assign add_ln77_1_fu_1053_p2 = ($signed(phi_mul5_reg_433) + $signed(sext_ln34_reg_1202));

assign add_ln77_fu_1064_p2 = (i_2_reg_422 + 5'd1);

assign add_ln79_fu_1133_p2 = (j_1_reg_444 + 5'd1);

assign add_ln81_fu_1143_p2 = (tmp_12_reg_1459 + zext_ln81_fu_1139_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign div22_fu_610_p3 = ((tmp_17_fu_570_p3[0:0] == 1'b1) ? p_neg_t_fu_594_p2 : tmp_5_fu_600_p4);

assign div2_fu_562_p3 = ((tmp_16_fu_522_p3[0:0] == 1'b1) ? p_neg_t5_fu_546_p2 : tmp_3_fu_552_p4);

assign div_fu_514_p3 = ((tmp_15_fu_474_p3[0:0] == 1'b1) ? p_neg_t11_fu_498_p2 : tmp_1_fu_504_p4);

assign empty_54_fu_871_p2 = (zext_ln54_1_fu_867_p1 + tmp_8_cast_reg_1237);

assign empty_57_fu_1083_p2 = (tmp1_fu_1078_p2 + zext_ln51_1_reg_1274);

assign empty_58_fu_1095_p2 = (tmp_13_fu_1088_p3 + ABC_read_reg_1167);

assign empty_fu_686_p2 = (p_cast16_fu_682_p1 + C_read_reg_1172);

assign gmem_0_AWLEN = 64'd16;

assign grp_fu_455_p0 = grp_fu_455_p00;

assign grp_fu_455_p00 = empty_54_reg_1328;

assign grp_fu_455_p1 = sext_ln34_1_reg_1208;

assign icmp_ln34_fu_655_p2 = (($signed(zext_ln34_fu_651_p1) < $signed(div_reg_1187)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_727_p2 = (($signed(zext_ln37_fu_723_p1) < $signed(div2_reg_1192)) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_746_p2 = ((i_reg_322 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_785_p2 = ((j_reg_333 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_820_p2 = (($signed(zext_ln51_2_fu_816_p1) < $signed(div22_reg_1197)) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_851_p2 = ((i_1_reg_366 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_896_p2 = ((k_reg_377 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_1000_p2 = ((j_2_reg_399 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_1017_p2 = ((j_3_reg_411 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_1058_p2 = ((i_2_reg_422 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_1127_p2 = ((j_1_reg_444 == 5'd16) ? 1'b1 : 1'b0);

assign p_cast13_fu_1074_p1 = phi_mul5_reg_433;

assign p_cast16_fu_682_p1 = tmp_7_fu_674_p3;

assign p_cast5_cast_fu_713_p1 = $signed(p_cast5_fu_703_p4);

assign p_cast5_fu_703_p4 = {{empty_fu_686_p2[63:2]}};

assign p_neg3_fu_530_p1 = P;

assign p_neg3_fu_530_p2 = ($signed(32'd0) - $signed(p_neg3_fu_530_p1));

assign p_neg9_fu_482_p2 = (32'd0 - N);

assign p_neg_fu_578_p1 = M;

assign p_neg_fu_578_p2 = ($signed(32'd0) - $signed(p_neg_fu_578_p1));

assign p_neg_t11_fu_498_p2 = (28'd0 - tmp_fu_488_p4);

assign p_neg_t5_fu_546_p2 = (28'd0 - tmp_2_fu_536_p4);

assign p_neg_t_fu_594_p2 = (28'd0 - tmp_4_fu_584_p4);

assign sext_ln34_1_fu_622_p0 = M;

assign sext_ln34_1_fu_622_p1 = sext_ln34_1_fu_622_p0;

assign sext_ln34_2_fu_626_p0 = P;

assign sext_ln34_2_fu_626_p1 = sext_ln34_2_fu_626_p0;

assign sext_ln34_fu_618_p0 = P;

assign sext_ln34_fu_618_p1 = sext_ln34_fu_618_p0;

assign sext_ln59_1_fu_913_p1 = $signed(add_ln59_1_fu_908_p2);

assign sext_ln59_fu_958_p1 = $signed(trunc_ln59_1_fu_948_p4);

assign sext_ln62_fu_990_p1 = $signed(trunc_ln2_fu_980_p4);

assign sext_ln79_fu_1110_p1 = $signed(trunc_ln_fu_1100_p4);

assign shl_ln1_fu_968_p3 = {{add_ln59_5_reg_1366}, {2'd0}};

assign shl_ln59_1_fu_935_p3 = {{add_ln59_3_fu_930_p2}, {2'd0}};

assign shl_ln_fu_762_p3 = {{jb_reg_310}, {4'd0}};

assign tmp1_fu_1078_p2 = ($signed(tmp_6_reg_1232) + $signed(p_cast13_fu_1074_p1));

assign tmp_10_fu_839_p3 = {{kb_reg_344}, {4'd0}};

assign tmp_11_fu_880_p3 = {{trunc_ln54_reg_1323}, {4'd0}};

assign tmp_12_fu_1120_p3 = {{trunc_ln77_reg_1442}, {4'd0}};

assign tmp_13_fu_1088_p3 = {{empty_57_reg_1447}, {2'd0}};

assign tmp_15_fu_474_p3 = N[32'd31];

assign tmp_16_fu_522_p1 = P;

assign tmp_16_fu_522_p3 = tmp_16_fu_522_p1[32'd31];

assign tmp_17_fu_570_p1 = M;

assign tmp_17_fu_570_p3 = tmp_17_fu_570_p1[32'd31];

assign tmp_1_fu_504_p4 = {{N[31:4]}};

assign tmp_2_fu_536_p4 = {{p_neg3_fu_530_p2[31:4]}};

assign tmp_3_fu_552_p1 = P;

assign tmp_3_fu_552_p4 = {{tmp_3_fu_552_p1[31:4]}};

assign tmp_4_fu_584_p4 = {{p_neg_fu_578_p2[31:4]}};

assign tmp_5_fu_600_p1 = M;

assign tmp_5_fu_600_p4 = {{tmp_5_fu_600_p1[31:4]}};

assign tmp_6_fu_666_p3 = {{phi_mul8_fu_172}, {4'd0}};

assign tmp_7_fu_674_p3 = {{ib_fu_176}, {6'd0}};

assign tmp_8_cast_fu_699_p1 = tmp_8_fu_691_p3;

assign tmp_8_fu_691_p3 = {{ib_fu_176}, {4'd0}};

assign tmp_9_fu_778_p3 = {{trunc_ln42_reg_1264}, {4'd0}};

assign tmp_fu_488_p4 = {{p_neg9_fu_482_p2[31:4]}};

assign tmp_s_fu_831_p3 = {{phi_mul2_reg_355}, {4'd0}};

assign trunc_ln2_fu_980_p4 = {{add_ln59_2_fu_975_p2[63:2]}};

assign trunc_ln42_fu_758_p1 = i_reg_322[3:0];

assign trunc_ln54_fu_863_p1 = i_1_reg_366[3:0];

assign trunc_ln59_1_fu_948_p4 = {{add_ln59_4_fu_943_p2[63:2]}};

assign trunc_ln59_fu_922_p1 = k_reg_377[3:0];

assign trunc_ln77_fu_1070_p1 = i_2_reg_422[3:0];

assign trunc_ln_fu_1100_p4 = {{empty_58_fu_1095_p2[63:2]}};

assign zext_ln34_fu_651_p1 = ib_fu_176;

assign zext_ln37_fu_723_p1 = jb_reg_310;

assign zext_ln46_1_fu_806_p1 = add_ln46_fu_801_p2;

assign zext_ln46_fu_797_p1 = j_reg_333;

assign zext_ln51_1_fu_774_p1 = shl_ln_fu_762_p3;

assign zext_ln51_2_fu_816_p1 = kb_reg_344;

assign zext_ln51_fu_770_p1 = shl_ln_fu_762_p3;

assign zext_ln54_1_fu_867_p1 = i_1_reg_366;

assign zext_ln54_fu_847_p1 = tmp_10_fu_839_p3;

assign zext_ln59_fu_926_p1 = trunc_ln59_fu_922_p1;

assign zext_ln62_fu_1012_p1 = j_2_reg_399;

assign zext_ln68_fu_1029_p1 = j_3_reg_411;

assign zext_ln70_1_fu_1043_p1 = add_ln70_1_reg_1404;

assign zext_ln70_fu_1034_p1 = j_3_reg_411;

assign zext_ln81_1_fu_1148_p1 = add_ln81_fu_1143_p2;

assign zext_ln81_fu_1139_p1 = j_1_reg_444;

always @ (posedge ap_clk) begin
    tmp_6_reg_1232[3:0] <= 4'b0000;
    tmp_8_cast_reg_1237[3:0] <= 4'b0000;
    tmp_8_cast_reg_1237[31] <= 1'b0;
    zext_ln51_reg_1269[3:0] <= 4'b0000;
    zext_ln51_reg_1269[35:31] <= 5'b00000;
    zext_ln51_1_reg_1274[3:0] <= 4'b0000;
    zext_ln51_1_reg_1274[61:31] <= 31'b0000000000000000000000000000000;
    tmp_9_reg_1279[3:0] <= 4'b0000;
    tmp_s_reg_1305[3:0] <= 4'b0000;
    zext_ln54_reg_1310[3:0] <= 4'b0000;
    zext_ln54_reg_1310[61:31] <= 31'b0000000000000000000000000000000;
    tmp_11_reg_1343[3:0] <= 4'b0000;
    tmp_12_reg_1459[3:0] <= 4'b0000;
end

endmodule //MM
