-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MM_writeTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_j_output_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    AB_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    AB_stream_empty_n : IN STD_LOGIC;
    AB_stream_read : OUT STD_LOGIC;
    AB_stream_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    AB_stream_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    m_axi_gmem3_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem3_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_WREADY : IN STD_LOGIC;
    m_axi_gmem3_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem3_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem3_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem3_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem3_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RVALID : IN STD_LOGIC;
    m_axi_gmem3_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem3_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem3_0_RLAST : IN STD_LOGIC;
    m_axi_gmem3_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem3_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_BVALID : IN STD_LOGIC;
    m_axi_gmem3_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem3_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    tmp_4 : IN STD_LOGIC_VECTOR (30 downto 0);
    bound6 : IN STD_LOGIC_VECTOR (57 downto 0);
    N_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    ABC_1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of MM_writeTiles_Pipeline_i_BLOCK_loop_j_BLOCK_loop_j_output_loop is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    constant ap_const_lv58_0 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv58_1 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv28_1 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv34_1 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln123_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal AB_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem3_blk_n_AW : STD_LOGIC;
    signal gmem3_blk_n_W : STD_LOGIC;
    signal gmem3_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal bound_fu_186_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal bound_reg_521 : STD_LOGIC_VECTOR (33 downto 0);
    signal icmp_ln125_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_530 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_530_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln130_fu_309_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln130_reg_535 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln130_fu_182_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln130_reg_540 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln130_1_fu_379_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln130_1_reg_545 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln130_1_reg_552 : STD_LOGIC_VECTOR (57 downto 0);
    signal AB_stream_read_reg_557 : STD_LOGIC_VECTOR (511 downto 0);
    signal sext_ln130_1_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal j_fu_112 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal j_1_fu_315_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal jb_fu_116 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    signal select_ln125_1_fu_289_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal indvar_flatten_fu_120 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    signal select_ln125_2_fu_327_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal ib_fu_124 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    signal select_ln123_1_fu_364_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal indvar_flatten20_fu_128 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000000";
    signal add_ln123_fu_232_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal icmp_ln127_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln123_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln123_fu_243_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal and_ln123_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln125_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal jb_2_fu_269_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln125_fu_281_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln130_1_fu_297_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln127_fu_305_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln125_1_fu_321_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln123_1_fu_358_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln_fu_371_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln130_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_401_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_fu_389_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln130_1_fu_411_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_6_fu_417_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal select_ln130_fu_426_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal shl_ln130_2_fu_434_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln130_fu_442_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln130_2_fu_446_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MM_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MM_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_1_1_U135 : component MM_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => N_1,
        din1 => add_ln130_reg_535,
        dout => mul_ln130_fu_182_p2);

    flow_control_loop_pipe_sequential_init_U : component MM_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ib_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ib_fu_124 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    ib_fu_124 <= select_ln123_1_fu_364_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten20_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten20_fu_128 <= ap_const_lv58_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln123_fu_218_p2 = ap_const_lv1_0))) then 
                    indvar_flatten20_fu_128 <= add_ln123_fu_232_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_120 <= ap_const_lv34_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln123_fu_218_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_120 <= select_ln125_2_fu_327_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_112 <= ap_const_lv5_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln123_fu_218_p2 = ap_const_lv1_0))) then 
                    j_fu_112 <= j_1_fu_315_p2;
                end if;
            end if; 
        end if;
    end process;

    jb_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    jb_fu_116 <= ap_const_lv28_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln123_fu_218_p2 = ap_const_lv1_0))) then 
                    jb_fu_116 <= select_ln125_1_fu_289_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                AB_stream_read_reg_557 <= AB_stream_dout;
                add_ln130_1_reg_545 <= add_ln130_1_fu_379_p2;
                mul_ln130_reg_540 <= mul_ln130_fu_182_p2;
                trunc_ln130_1_reg_552 <= add_ln130_2_fu_446_p2(63 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln130_reg_535 <= add_ln130_fu_309_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                    bound_reg_521(30 downto 0) <= bound_fu_186_p1(30 downto 0);
                icmp_ln125_reg_530 <= icmp_ln125_fu_238_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln125_reg_530_pp0_iter2_reg <= icmp_ln125_reg_530;
            end if;
        end if;
    end process;
    bound_reg_521(33 downto 31) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    AB_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, AB_stream_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            AB_stream_blk_n <= AB_stream_empty_n;
        else 
            AB_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    AB_stream_read_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            AB_stream_read <= ap_const_logic_1;
        else 
            AB_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    add_ln123_1_fu_358_p2 <= std_logic_vector(unsigned(ib_fu_124) + unsigned(ap_const_lv28_1));
    add_ln123_fu_232_p2 <= std_logic_vector(unsigned(indvar_flatten20_fu_128) + unsigned(ap_const_lv58_1));
    add_ln125_1_fu_321_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_120) + unsigned(ap_const_lv34_1));
    add_ln130_1_fu_379_p2 <= std_logic_vector(unsigned(mul_ln130_reg_540) + unsigned(shl_ln_fu_371_p3));
    add_ln130_2_fu_446_p2 <= std_logic_vector(unsigned(ABC_1) + unsigned(sext_ln130_fu_442_p1));
    add_ln130_fu_309_p2 <= std_logic_vector(unsigned(shl_ln130_1_fu_297_p3) + unsigned(zext_ln127_fu_305_p1));
    and_ln123_fu_263_p2 <= (xor_ln123_fu_251_p2 and icmp_ln127_fu_257_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter11, AB_stream_empty_n, m_axi_gmem3_0_BVALID)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem3_0_BVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_0 = AB_stream_empty_n)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter11, AB_stream_empty_n, m_axi_gmem3_0_AWREADY, m_axi_gmem3_0_WREADY, m_axi_gmem3_0_BVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem3_0_BVALID = ap_const_logic_0)) or ((m_axi_gmem3_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((m_axi_gmem3_0_AWREADY = ap_const_logic_0) or (ap_const_logic_0 = AB_stream_empty_n))));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter11, AB_stream_empty_n, m_axi_gmem3_0_AWREADY, m_axi_gmem3_0_WREADY, m_axi_gmem3_0_BVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem3_0_BVALID = ap_const_logic_0)) or ((m_axi_gmem3_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((m_axi_gmem3_0_AWREADY = ap_const_logic_0) or (ap_const_logic_0 = AB_stream_empty_n))));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter11, AB_stream_empty_n, m_axi_gmem3_0_AWREADY, m_axi_gmem3_0_WREADY, m_axi_gmem3_0_BVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem3_0_BVALID = ap_const_logic_0)) or ((m_axi_gmem3_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and ((m_axi_gmem3_0_AWREADY = ap_const_logic_0) or (ap_const_logic_0 = AB_stream_empty_n))));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln123_fu_218_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln123_fu_218_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter10_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter10_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bound_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4),34));

    gmem3_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem3_0_AWREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem3_blk_n_AW <= m_axi_gmem3_0_AWREADY;
        else 
            gmem3_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem3_0_BVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem3_blk_n_B <= m_axi_gmem3_0_BVALID;
        else 
            gmem3_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_gmem3_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem3_blk_n_W <= m_axi_gmem3_0_WREADY;
        else 
            gmem3_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln123_fu_218_p2 <= "1" when (indvar_flatten20_fu_128 = bound6) else "0";
    icmp_ln125_fu_238_p2 <= "1" when (indvar_flatten_fu_120 = bound_reg_521) else "0";
    icmp_ln127_fu_257_p2 <= "1" when (j_fu_112 = ap_const_lv5_10) else "0";
    j_1_fu_315_p2 <= std_logic_vector(unsigned(select_ln125_fu_281_p3) + unsigned(ap_const_lv5_1));
    jb_2_fu_269_p2 <= std_logic_vector(unsigned(select_ln123_fu_243_p3) + unsigned(ap_const_lv28_1));
    m_axi_gmem3_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem3_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem3_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem3_0_ARID <= ap_const_lv1_0;
    m_axi_gmem3_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem3_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem3_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem3_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem3_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem3_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem3_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem3_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem3_0_AWADDR <= sext_ln130_1_fu_461_p1;
    m_axi_gmem3_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem3_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem3_0_AWID <= ap_const_lv1_0;
    m_axi_gmem3_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem3_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem3_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem3_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem3_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem3_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem3_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem3_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem3_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem3_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem3_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem3_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem3_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem3_0_RREADY <= ap_const_logic_0;
    m_axi_gmem3_0_WDATA <= AB_stream_read_reg_557;
    m_axi_gmem3_0_WID <= ap_const_lv1_0;
    m_axi_gmem3_0_WLAST <= ap_const_logic_0;
    m_axi_gmem3_0_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_gmem3_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem3_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem3_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem3_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln125_fu_275_p2 <= (icmp_ln125_fu_238_p2 or and_ln123_fu_263_p2);
    select_ln123_1_fu_364_p3 <= 
        add_ln123_1_fu_358_p2 when (icmp_ln125_reg_530_pp0_iter2_reg(0) = '1') else 
        ib_fu_124;
    select_ln123_fu_243_p3 <= 
        ap_const_lv28_0 when (icmp_ln125_fu_238_p2(0) = '1') else 
        jb_fu_116;
    select_ln125_1_fu_289_p3 <= 
        jb_2_fu_269_p2 when (and_ln123_fu_263_p2(0) = '1') else 
        select_ln123_fu_243_p3;
    select_ln125_2_fu_327_p3 <= 
        ap_const_lv34_1 when (icmp_ln125_fu_238_p2(0) = '1') else 
        add_ln125_1_fu_321_p2;
    select_ln125_fu_281_p3 <= 
        ap_const_lv5_0 when (or_ln125_fu_275_p2(0) = '1') else 
        j_fu_112;
    select_ln130_fu_426_p3 <= 
        sub_ln130_1_fu_411_p2 when (tmp_fu_389_p3(0) = '1') else 
        tmp_6_fu_417_p4;
        sext_ln130_1_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln130_1_reg_552),64));

        sext_ln130_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln130_2_fu_434_p3),64));

    shl_ln130_1_fu_297_p3 <= (select_ln125_1_fu_289_p3 & ap_const_lv4_0);
    shl_ln130_2_fu_434_p3 <= (select_ln130_fu_426_p3 & ap_const_lv6_0);
    shl_ln_fu_371_p3 <= (select_ln123_1_fu_364_p3 & ap_const_lv4_0);
    sub_ln130_1_fu_411_p2 <= std_logic_vector(unsigned(ap_const_lv28_0) - unsigned(tmp_5_fu_401_p4));
    sub_ln130_fu_396_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(add_ln130_1_reg_545));
    tmp_5_fu_401_p4 <= sub_ln130_fu_396_p2(31 downto 4);
    tmp_6_fu_417_p4 <= add_ln130_1_reg_545(31 downto 4);
    tmp_fu_389_p3 <= add_ln130_1_reg_545(31 downto 31);
    xor_ln123_fu_251_p2 <= (icmp_ln125_fu_238_p2 xor ap_const_lv1_1);
    zext_ln127_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln125_fu_281_p3),32));
end behav;
